### ISSUE TITLE
files to be code reviewed for a11y

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#102]
I'm using this issue to keep track of which source files have been modified/added as the result of #57 (Instrument with accessibility).   This will be useful for whoever does code review.

As of Tue May 21 14:31:24 MDT 2019

### New files:
ConcentrationDescriber
SoluteAmountDescriber
SoluteDescriber
VolumeDescriber
MolarityKeyboardHelpContent
MolarityScreenSummaryNode
MolarityA11yStrings
molarity_a11y_view.html

### Modified files:
BeakerNode
MolarityScreenView
SoluteComboBox
VerticalSlider
MSymbols
molarity-strings_en.json

**Comment by twant** [comment]
One new file added: MolarityBeakerDescriptionNode

**Comment by twant** [comment]
Documented in a comment in #112, closing this one to consolidate.
