### ISSUE TITLE
rename MConstants and MSymbols

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#103]
From the code-review checklist:

> - [ ] Do filenames use an appropriate prefix? Some filenames may be prefixed with the repository name, e.g. MolarityConstants.js in molarity. If the repository name is long, the developer may choose to abbreviate the repository name, e.g. EEConstants.js in expression-exchange. If the abbreviation is already used by another respository, then the full name must be used. For example, if the "EE" abbreviation is already used by expression-exchange, then it should not be used in equality-explorer. Whichever convention is used, it should be used consistently within a repository - don't mix abbreviations and full names.

This sim mixes "Molarity" and "M" prefixes, more of the former than the latter.  So to bring this sim up to PhET code standards, `MConstants` and `MSymbols` should be renamed `MolarityConstants` and `MolaritySymbols` respectively.

**Comment by pixelzoom** [comment]
@twant is it going to disrupt any a11y work if I proceed with this?  I don't want to cause a conflict with any work-in-progress or branches that may need to be merged.  Let me know when it's convenient for me to so this work.  Thanks.

**Comment by twant** [comment]
@pixelzoom I don't think this will affect the a11y work -- thanks for checking!

**Comment by twant** [comment]
@pixelzoom and @zepumph I just renamed both files. Closing for now, but please let me know if you'd like to reopen and review these changes!
