### ISSUE TITLE
branch: refactor-solution-describer

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#104]
This branch was created with on 4/5/19 by @twant with no associated GitHub issue.   Please describe the purpose of this branch.

**Comment by twant** [comment]
This branch was created to move away from one monolithic MolarityDescriber and toward several smaller describers (i.e. ConcentrationDescriber, VolumeDescriber, etc.). I believe that refactor is complete -- closing and deleting the branch.
