### ISSUE TITLE
Combobox Alerts

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#105]
We have updated the design doc to indicate some changes to the combobox alerts. Here are those changes copied in:

- [x] **When solute is changed from ‘not saturated’ solution to a ‘not saturated’ solution:**
 New solution. {{Drink Mix}} concentration readout range {{0.00}} to {{5.0 M}}

- [x] **From a ‘saturated’ solution to a ‘not saturated’ solution:**
New solution. Not saturated, no solids. Solution {{very concentrated}}. 

- [x] **From a ‘not saturated’ or from a ‘saturated’ solution to a ‘saturated’ solution:**
New solution. Saturated, {{a lot of}} solids. Beyond max concentration.

There's also a comment pointing out these string changes in the design doc.

**Comment by twant** [comment]
@emily-phet @Matthew-phet I believe this issue, along with#82, #92, #93, and #96 have been implemented and pushed to master. Assigning back over to you for review!
https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.13/phet/molarity_en_phet.html
