### ISSUE TITLE
Simplify initial alerts/descriptions

### ISSUE THREAD

**Issue by twant** [phetsims/molarity#108]
Need to find a way to make the initial alert system simpler (maybe in the alert manager)?

**Comment by twant** [comment]
@zepumph @jessegreenberg is there a way to get the last utterance that was read from the utteranceQueue? I'm looking for an alternative to a focus alert, so one of my thoughts is to see if the last utterance was one that came from the same slider. I see a way to get the whole queue, but I'm not sure to see where the screen reader is in the process of reading alerts (is it safe to assume that the last utterance in the queue is always the last one read?).

**Comment by terracoda** [comment]
@twant could you say explicitly what focus alerts you are trying to phase out? A lot of iteration has occurred and @Matthew-phet and @terracoda are not sure what focus alerts you are referring to?

**Comment by twant** [comment]
@zepumph @terracoda:

@Matthew-phet and I decided to phase out the aria value text that initially shows up when a slider is focused. Previously, the first time a slider was focused the aria value text was "0.600 liters in beaker" and then when the slider was moved, the aria value text would change to the shorter "0.650 liters." @Matthew-phet recommended removing the initial aria value text (and the need to use a focus event) and just have it be "0.600 liters". Let us know if you have questions!

**Comment by terracoda** [comment]
@twant, that's perfect.
In GFLB, I also had to adjust all my "special on-focus" aria-valuetext values due to the lack of focus events in iOS.

I think not relying on focus events actually made the design better.
I think it is ok to close this issue.
