### ISSUE TITLE
Beaker description redesign changes

### ISSUE THREAD

**Issue by Matthew-phet** [phetsims/molarity#109]
Here are all the new changes and ill put the old one at the bottom

**New Changes**
**Example when qualitative and saturated, values unchecked**
Beaker is {{nearly full of}} a {{potassium permanganate}} solution. The solution is: 

- {{purple}}
- contains {{a lot of}} {{potassium permanganate}} 
- {{is saturated}} with {{a lot of}} solids
- {{is max concentration}}
- chemical formula of {{potassium permanganate}} is {{KMnO4}}.
- Concentration readout range {{0.00}} to {{0.500}}

**Example when qualitative and NOT saturated, values unchecked**
Beaker is {{nearly full of}} a {{potassium permanganate}} solution. The solution is: 

- {{purple}}
- contains {{some}} {{potassium permanganate}} 
- {{is very concentration}}
- chemical formula of {{potassium permanganate}} is {{KMnO4}}.
- Concentration readout range {{0.00}} to {{0.500}}

**Example when quantitative and saturated, values checked**
Beaker has 0.200 liters of a {{potassium permanganate}} solution. The solution is: 

- {{purple}}
- contains {{0.123}} mols of {{potassium permanganate}} 
- concentration {{0.500}} molar
- {{is saturated}} with {{a lot of solids}}
- chemical formula of {{potassium permanganate}} is {{KMnO4}}.
- Concentration readout range {{0.00}} to {{0.500}}

**Example when quantitative and NOT saturated, values checked**
Beaker has 0.882 liters of a {{potassium permanganate}} solution. The solution is: 

- {{purple}}
- contains {{0.195}} mols of {{potassium permanganate}} 
- concentration {{0.221}} molar
- chemical formula of {{potassium permanganate}} is {{KMnO4}}.
- Concentration readout range {{0.00}} to {{0.500}}

**When solution is pure water, values checked**
Beaker has 0.882 liters of water. The solution is: 

- {{clear}}
- contains {{0.000}} mols of {{potassium permanganate}} 
- chemical formula of {{potassium permanganate}} is {{KMnO4}}.
- Concentration readout range {{0.00}} to {{0.500}}

**When solution is pure water, values unchecked** 

- Beaker is {{nearly full of}} a water. The solution is: 
- {{clear}}
- contains {{zero}} {{potassium permanganate}} 
- chemical formula of {{potassium permanganate}} is {{KMnO4}}.
- Concentration readout range {{0.00}} to {{0.500}}

**Solute colors**
1. {{Drink Mix}} = {{red}} 
2. {{Cobalt(II) nitrate}} = {{red}} 
3. {{Cobalt(II) chloride}} = {{pink}}
4. {{Potassium dichromate}} = {{orange}}
5. {{Gold(III) chloride}} = {{gold}}
6. {{Potassium chromate}} = {{yellow}}
7. {{Nickel(II) chloride}} = {{green}}
8. {{Copper(II) sulfate}} = {{blue}}
9. {{Potassium permanganate}} = {{purple}}

**Old beaker description**
**Case 1:** 
Solution Concentration of drink mix‬ Is not concentrated. Concentration readout range is 0.00 to 5.95 Molar. Drink mix contains mainly citric acid, which has a chemical formula of C6H8O7

Solution concentration of {{soluteProperty}} is {{concentrationProperty}}. Concentration readout range is {{0.00}} to {{5.0}} molar. The chemical formula for {{soluteProperty}} is {{chemicalFormulaPattern}}.

**Case 2**: when solute is zero
Beaker {{volumeProperty}} of water, containing no solute.

**Values Checked
Case 1:**
Solution Concentration of ‪drink mix‬ Is not concentrated. Concentration readout range is 0.00 to 5.95 Molar. Drink mix contains mainly citric acid, which has a chemical formula of C6H8O7.

Solution concentration of {{soluteProperty}} is {{concentrationProperty}}. Concentration readout range is {{0.00}} to {{5.0}} molar. The chemical formula for {{soluteProperty}} is {{chemicalFormulaPattern}}.

**Case 2**: when solute is zero
Beaker {{volumeProperty}} of water, containing no solute.

**Values Checked
Case 1:**
Solution Concentration of ‪Drink mix‬ Is 1.000 Molar. Concentration readout range is 0.00 to 5.95 Molar. Drink mix contains mainly citric acid, which has a chemical formula of C6H8O7

Solution concentration of {{soluteProperty}} is {{concentrationProperty}} molar. Concentration readout range is {{0.00}} to {{5.0}} molar. The chemical formula for {{soluteProperty}} is {{chemicalFormulaPattern}}.

**Case 2:** no solute (new special case)
Beaker {{has volumeProperty}} liters of water, containing no solute.

**Comment by terracoda** [comment]
@Matthew-phet, is there a reason why you moved the color parameter into a bullet of it's own? I personally think it is best to keep the list of details as short as possible, but if you move color into a bullet, you also need to move the verb, so the first bullet becomes:
- is {{purple}}

I'm going to work out the same scenarios for Drink Mix in the design doc.

**Comment by terracoda** [comment]
@Matthew-phet, as you know I have 4 drink mix examples in the design doc. I think we will refine a couple things in your examples next.

**Comment by twant** [comment]
Quick question about this: I'm noticing that most of the bullet points grammatically don't make sense with the start of the sentence being "The solution is:" 

Is there a different way you'd like to start this list of properties, @Matthew-phet?

**Comment by terracoda** [comment]
@twant, @Matthew-phet and I had not finished cleaning up the examples in the design doc (sorry).

**Comment by terracoda** [comment]
I am going to remake the potassium permanganate example, so it is in the same format as teh drink mix example, then @Matthew-phet can make sure it is what he wants (what we agreed on).

**Comment by terracoda** [comment]
@Matthew-phet, @emily-phet and @twant, I made a new set of examples for the Potassium Permanganate in the same format as the set I made for the Drink Mix solute.

@Matthew-phet, could you review both sets.

I made some suggested changes to the scales (last week) which I don't think we have discussed.

In addition, while I was adjusting the Potassium Permanganate examples, I came up with possible new phrasing for the bullet item containing the description of the concentration read out range. And in so doing, I now realize why I was so uncomfortable with the description of the read out. If we include it, we are basically describing concentration twice.

I am fine going with your plan (and describing the exact read out range), but I have also included my alternatives that we could discuss tomorrow if you are available, or Tuesday in our regular meeting.

You'll see that the suggested new phrasing has some challenges (i.e., describing the location of the concentration arrow) which we have said we do not want to get into. With that said, however, I think the suggested alternatives shed some light on how describing the read out range directly is not directly in synch with the visual representations which could cause some confusion.

I'll change the label to meeting, so we can discuss.

**Comment by terracoda** [comment]
@twant, I unassigned you because it is not clear to me the examples in the design doc are clean enough yet for you to implement.

Ignoring any new alternative suggestions that I marked in red and put in sub-bullets, the phrasing should all be correct now. That said, I would like @Matthew-phet to go over the set of examples for Drink Mix and the set for Potassium Permanganate once again before implementation.

**Comment by terracoda** [comment]
@twant, @Matthew-phet and I will discuss the changes before yours and @Matthew-phet 's meeting on Tuesday :-)

**Comment by terracoda** [comment]
@twant, @Matthew-phet, @emily-phet and I discussed changes to the Beaker's dynamic description. There are 4 examples for Drink Mix and 4 examples for Potassium Permanganate, and each example is shown in both states (Values not checked and Values checked).

The **Drink Mix** examples are available in the main part of the PDOM, under the H3: Beaker heading, here [BEAKER’S DYNAMIC STATE DESCRIPTION](https://docs.google.com/document/d/1Z_5biEOBk9W4lVPXxGt7fyg-V6_CwTA4vMZ0mVMTJsI/edit#heading=h.1qoluoqfetdv).

More examples are down under [Dynamic States for the Beaker (new examples)](https://docs.google.com/document/d/1Z_5biEOBk9W4lVPXxGt7fyg-V6_CwTA4vMZ0mVMTJsI/edit#heading=h.uwocbwbntu3x) 

Please note that there have been changes to most of the descriptive scales (Solute Amount, Solution Volume, Concentration Level), so some values are highlighted in yellow as I was guessing as what they might be once the new scales are implemented in accordance with the model.

The new scales have been verified by @Matthew-phet are now in Tables in the Dynamic State Descriptions section under [Dynamic Parameters & Ranges](https://docs.google.com/document/d/1Z_5biEOBk9W4lVPXxGt7fyg-V6_CwTA4vMZ0mVMTJsI/edit#heading=h.3cpn3depkkhq) heading.

Please let us know if anything is unclear, and thanks for all your hard work.

**Comment by terracoda** [comment]
@twant, and if you have not discussed all this with @Matthew-phet, it might be best to do that first ;-)

**Comment by terracoda** [comment]
@twant, @Matthew-phet mentioned you would like a new issue for this issue, so I am assigning back to myself to split the issue up into smaller issues.

I'll make a issues for the new scales, and a separate issue for the changes to the beaker's description if that's needed.

**Comment by terracoda** [comment]
This issue will be handled in in #121 , and #115, #116, #117.
So closing.
