### ISSUE TITLE
Add sound

### ISSUE THREAD

**Issue by jbphet** [phetsims/molarity#110]
The sound design has been approved, it's time to add it to the sim.  The sound design document is available [here](https://docs.google.com/document/d/1J05jC0mWOBz7S3FWTjVMvs7CiYpXibi5trA6xABPYw8/edit?usp=sharing) and the most recent sound design prototype is [here](https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.114/phet-io-wrapper-sonification/molarity/html/molarity-sonification.html?sonificationFile=sonificationOptions&accessibility&precipitateSound=2).

**Comment by jbphet** [comment]
I've added most of the sounds for this, and it's time for @Ashton-Morris to take it for a test drive and let me know what should be changed about the mix.  The volume settings are pretty distributed in the code, so @Ashton-Morris - I think it would be best if you just provided me with written feedback about what should go up and down and by how much in this GitHub issue and then I'll do the best I can to implement it in the code.

**Comment by Ashton-Morris** [comment]
Overall it sounds very good. The change I would make is: Lower the precipitate by 30%

Also I am not getting a sound for when you close the combobox without choosing a new Solute.

And when I change the water level with no solute, it sounds like that sound is not going through the same reverb as all of the other sounds. That sound much more mono while all the other sounds sounds wider.

**Comment by jbphet** [comment]
>  Lower the precipitate by 30%

I've done this, and I also fixed an issue where the sound was playing infrequently compared to the sound design prototype.  In the end, I also tweaked the volume a bit more to match the sound design prototype pretty closely.

> I am not getting a sound for when you close the combobox without choosing a new Solute.

@Ashton-Morris, @emily-phet, and I discussed this in the most recent sound design meeting, but I thought I'd record it here too so that we have a record of the information.  The problem with playing a sound when the combo box closes is that the close event occurs before the change to the selected value (in this case the selected solute), so the code to play a sound when the combo box is opened and closed but no selection change occurs is a bit tricky.  It could be done, but I proposed that we leave it like this for now and wait until the sound generation functionality is fully integrated into the `Combobox` common code, at which point this will be easier.  The team agreed that this was okay.

> [W]hen I change the water level with no solute, it sounds like that sound is not going through the same reverb as all of the other sounds. That sound much more mono while all the other sounds sounds wider.

The sounds are both going through exactly the same reverb signal path.  I suspect that it sounds the way it does because the marimba sound being used for the concentration is one of the few stereo sounds that we have.  I believe we left this one as a stereo sound because we use it a lot and it sounds good that way, but I'm not certain.  So, for this one, the easiest ways to address it are to:
+ leave it as is
+ make the marimba sound used for concentration into a mono sound
+ make the low marimba sound used for changes to solution level with no solute into a stereo sound
+ we might be able to make some adjustments to the volume levels to make it sound more consistent

@Ashton-Morris - please let me know which of the options sounds best to you.

Here is the latest dev version, which includes the changes to the precipitate sound generator:
https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.16/phet/molarity_en_phet.html

**Comment by Ashton-Morris** [comment]
@jbphet I am getting a 404 error even when connected through the vpn. Can you verify that this link is working?

**Comment by jbphet** [comment]
My bad - I had accidentally deployed the phet-io brand instead of the phet brand.  The link should be good now.

**Comment by jbphet** [comment]
The latest implementation of the sound was reviewed in the 7/9/2018 sound design meeting, and we've decided that it's good to go.  Assigning to @twant, and she is working on the publication of this sim with support from @zepumph.

**Comment by twant** [comment]
Thanks so much @jbphet! Everything sounds great -- closing.
