### ISSUE TITLE
New description scale for Solution Volume

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#115]
@twant, the described qualitative scales for Solution Volume, Solute Amount, and Concentration Levels have changed. The changed descriptions are bolded. Assigning to @Matthew-phet to verify and assign to you.

Here are the changes to Solution Volume

New Descriptions | New Solution Volume Range in liters (L)
-- | --
{{is full}} | 1.000 L
{{is nearly full}} | 0.751 L to 0.999 L
{{is over half full}} | 0.501 L to 0.750 L
**{{is half full}}** | 0.500 L
{{is under half full}} | 0.351L to 0.499 L
**{{is nearly empty}}** | 0.201 L to 0.350 L
**{{is at lowest amount}}** | 0.200 L

For a side by side comparison of the old descriptions and original ranges, please see design doc [Table: Values describing Solution Volume (changed)](https://docs.google.com/document/d/1Z_5biEOBk9W4lVPXxGt7fyg-V6_CwTA4vMZ0mVMTJsI/edit#heading=h.e5dnae25vb00)

**Edited July 2, 2019**
- changed description of lowest volume from: {{has lowest amount of}} to {{is at lowest amount}}

**Comment by Matthew-phet** [comment]
looks good! assigning to @twant

**Comment by terracoda** [comment]
@Matthew-phet and I also discussed more balanced ranges in today's design meeting. @Matthew-phet, please share section **2. Key presses for sliders not balanced across ranges** in the [Agenda doc](https://docs.google.com/document/d/105AnA7Z-TbwIGTHyHQCxK-ZNc9LwfjsQx9UtmMBnTHc/edit#heading=h.7ygy7f7fi07m) with @twant.

Apologies that my original suggested ranges were not very balanced.

**Comment by terracoda** [comment]
@twant, check #128 for more details about the ranges and key presses. Apologies for multiple issues.

**Comment by twant** [comment]
@terracoda and @Matthew-phet am I right in thinking that the only remaining change for this one is the key press balancing from #128? If so, okay with you if I close this one so we consolidate to one issue?

**Comment by terracoda** [comment]
Descriptions and ranges seem good. Thanks @twant. Closing.

**Comment by terracoda** [comment]
Just adding that Solution Volume description scale, ranges, and key presses look good. Issues for corresponding concentration levels are mentioned in #117, and will be dealt with there.
