### ISSUE TITLE
New description scale for Solute Amount

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#116]
@twant, related to #115, there are changes to Solute Amount, too. @Matthew-phet, please assign to @twant.

Here are the changes to Solution Volume. "zero" was changed to "no".

Description | Range for moles
-- | --
{{max amount of}} | 1.000 moles
{{a lot of}} | 0.850 to 0.950 moles
{{a bunch of}} | 0.650 to 0.800 moles
{{some}} | 0.450 to 0.600 moles
{{a low amount of}} | 0.200 to 0.400 moles
{{a little}} | 0.001 to 0.150 moles
**{{no}}** | 0.000 moles

**Comment by Matthew-phet** [comment]
looks good to me! assigning to @twant

**Comment by terracoda** [comment]
@twant, I think these are clear just assigning back to you and removing meeting label.

**Comment by terracoda** [comment]
Actually, sorry, I pointed out to @Matthew-phet in our meeting today that the current implementation doesn't result in a nice balanced keyboard experience (the number of steps for each range vary a lot).

@Matthew-phet, can you update this issue with the steps we discussed and re-assign to @twant.

**Comment by terracoda** [comment]
See section 2. Key presses for sliders not balanced across ranges in the Agenda doc (https://docs.google.com/document/d/105AnA7Z-TbwIGTHyHQCxK-ZNc9LwfjsQx9UtmMBnTHc/edit#heading=h.7ygy7f7fi07m)

**Comment by terracoda** [comment]
And apologies my original suggested ranges were not very balanced.

**Comment by terracoda** [comment]
Key presses are being handled in #128

**Comment by terracoda** [comment]
@twant, can you add labels "status: ready-to-review" when you have all the scales implemented?

**Comment by terracoda** [comment]
In https://github.com/phetsims/molarity/issues/121, I noticed extra "of", and just removed it https://github.com/phetsims/molarity/commit/c4843307401f31cecb7d443026096edc5581f3c2

Apologies, I forgot to make a commit comment!

**Comment by terracoda** [comment]
@twant, the Solute description scale, ranges, and key presses seem good to me.
As notes in #117, there are issues with the concentrations levels.

Closing this issue.
