### ISSUE TITLE
Change initial interaction hint and put in new paragraph

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#118]
Please change the initial interaction hint to be a little more playful and a little less wordy:
**Current wording:** 
- Play with solute amount and solution volume to explore changes to the concentration of different solutions.

**New wording:**
- Play with solution in beaker and observe changes to concentration.

In addition, please place this help text in it's own paragraph. It makes it harder to miss on first read through and easier skip on subsequent read through's. 

@Matthew-phet, please verify and assign to @twant.

**Comment by Matthew-phet** [comment]
looks good to me! assigning to @twant

**Comment by terracoda** [comment]
@Matthew-phet this is implemented and looks and sounds good.
Thanks @twant! Verfied and closing.
