### ISSUE TITLE
Combine and change help text for Solution Controls

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#119]
I had a comment from a screen reader consultant that the help text for the solute amount and solution volume sliders was a bit repetitive.

**Please remove the current help text for each slider:**
- Explore how changing Solute Amount affects solution in beaker.
- Explore how changing Solution Volume affects solution in beaker.

**Please create a paragraph for one combined help text** for all the Solution Controls. Put the help text under the Solution Controls (h3) heading.
- Solute amount and solution volume allow changes to chosen solution.

The goal of this help text is to make it clear that playing with both Solute Amount and Solution Volume are useful things to do, and to also hint at the fact that the solution can be changed (i.e., the solute can be changed).

@Matthew-phet please assgin to @twant when ready.

**Comment by Matthew-phet** [comment]
looks good to me! assigning to @twant

**Comment by terracoda** [comment]
@Matthew-phet, I just verified this change. It looks good! Awesome work @twant! Thanks.
