### ISSUE TITLE
Change help text for Solute combobox

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#120]
Related to #118, #119, please also change the help text for the Solute combobox interaction.

**Current help text:**
- Choose one of nine solutes to play with in beaker.

**Change to:**
- Choose a different solute for beaker. 

Because, we mention the nine solutes in the opening screen summary and the solute items are numbered naturally (1 of 9, 2 of 9, etc.) when the combobox's listbox is opened, it is not necessary to mention again in the help text that there are 9 different solutes.

@Matthew-phet please assign to @twant when ready.

**Comment by Matthew-phet** [comment]
looks good to me! assigning to @twant

**Comment by terracoda** [comment]
@Matthew-phet, I just verified the change. It looks good. Thanks @twant. Closing issue.
