### ISSUE TITLE
Changes to Beaker description in Play Area

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#121]
Based on our discussion in #109, in the design doc and in meetings, we are changing the phrases that make up the Beaker's dynamic description in the Play Area. 

In the design doc, there are 4 [Drink Mix examples](https://docs.google.com/document/d/1Z_5biEOBk9W4lVPXxGt7fyg-V6_CwTA4vMZ0mVMTJsI/edit#heading=h.1qoluoqfetd) and 4 [Potassium Permanganate examples](https://docs.google.com/document/d/1Z_5biEOBk9W4lVPXxGt7fyg-V6_CwTA4vMZ0mVMTJsI/edit#heading=h.9ca56wbjeb4), and each example is shown in both states (Values not checked and Values checked).

I will copy the required examples into this issue, but for reference and more detail please see the above links to the design doc examples.

Please see issues #115, #116, and #117 for new description scales that will go in the beaker's description.

**Comment by terracoda** [comment]
The dynamic state description for the Beaker is housed in a paragraph and a dynamic list. I think the basic structure is already in place, but there are changes to number of items and where the details go.

Drink Mix is a bit of an edge case as it never saturates and does not have a chemical formula. This items are left out of the list for Drink Mix.

## Drink Mix
### Sim startup values
**Values NOT checked (qual. values)**
Beaker {{is half full of}} {{a drink mix}} solution. The {{red}} solution: 
- contains {{some}} {{drink mix}} 
- {{is not very concentrated}}
- concentration readout range {{0}} to {{5.0}} molar

**Values checked (quant. values) (Sim startup values)**
Beaker {{has 0.500 liters of}} {{a drink mix}} solution. The {{red}} solution: 
- contains {{0.500}} moles of}} {{drink mix}} 
- concentration {{1.000}} molar
- concentration readout range {{0}} to {{5.0}} molar

### Solute slider maxxed and volume minned
**Values NOT checked (qual. values**) 
Beaker {{has lowest amount of}} {{a drink mix}} solution. The {{red}} solution:
- contains {{max amount of}} {{drink mix}} 
- {{is highly concentrated}} (**Note:** at max solute amount, but not at max concentration!)
- concentration readout range {{0}} to {{5.0}} molar

**Values checked (quant. values)**
Beaker {{has 0.200 liters of}} {{a drink mix}} solution. The {{red}} solution: 
- contains {{1.000 moles of}} {{drink mix}} 
- concentration {{5.000}} molar
- concentration readout range {{0}} to {{5.0}} molar

### Random change to each slider (low solute, high volume)
**Values checked (qual. values)** 
Beaker {{nearly full of}} {{a drink mix}} solution. The {{red}} solution:
- contains {{a low amount of}} {{drink mix}} 
- {{is slightly concentrated}}
- concentration readout range {{0}} to {{5.0}} molar

**Values checked (quant. values) (random change)**
Beaker {{has 0.850 liters of}} {{a drink mix}} solution. The {{red}} solution:
- contains {{0.195 mol of}} {{drink mix}} 
- concentration {{0.229}} molar
- concentration readout range {{0}} to {{5.0 molar}} 

### Zero solute (pure water)
**Values NOT checked (qual. values)** 
Beaker {{is nearly full of}} {{pure water}}. The {{clear}} solution: 
- contains {{no}} {{drink mix}}
- chemical formula of {{pure water}} is {{H2O}}
- concentration readout range {{0}} to {{5.0}} molar

**Values checked (quant. values)**
Beaker {{has 0.882 liters of}} {{pure water}}.  The {{clear}} solution: 
- contains {{0.000}} mol of {{drink mix}} 
- concentration {{0.000}} molar
- chemical formula of {{pure water}} is {{H2O}}
- concentration readout range {{0}} to {{5.0 molar}}

**Note** that chemical formula's are not accurately display here, but are already correct in the sim.

**Comment by terracoda** [comment]
## Potassium Permanganate examples
### Sim start-up values (just changed solute)
**Values NOT checked (qual. values)**
Beaker {{is half full of}} {{a potassium permanganate}} solution. The {{purple}} solution: 
- contains {{some}} {{potassium permanganate}} 
- {{is saturated with a few solids}}
- {{has max concentration}}
- chemical formula of {{potassium permanganate}} is {{KMnO4}}
- concentration readout range {{0.00}} to {{0.500}}

**Values checked (quant. values) (Sim start-up values)**
Beaker {{has 0.500 liters of}} {{a potassium permanganate}} solution. The {{purple}} solution: 
contains {{0.500}} moles of}} {{potassium permanganate}} 
- {{is saturated}} with {{a few solids}}
- concentration {{0.500}} molar
- chemical formula of {{potassium permanganate}} is {{KMnO4}}
- concentration readout range {{0.00}} to {{0.500}}

### Solution Volume minned and Solute Amount maxxed
**Values NOT checked (qual. values)** 
Beaker {{has lowest amount of}} {{a potassium permanganate}} solution. The {{purple}} solution: 
- contains {{max amount of}} {{potassium permanganate}} 
- {{is saturated}} with {{a lot of solids}}
- {{has max concentration}}
- chemical formula of {{potassium permanganate}} is {{KMnO4}}
- concentration readout range {{0}} to {{0.500}} molar

**Values checked (quant. values)**
Beaker {{has 0.200 liters of}} {{a potassium permanganate}} solution. The {{purple}} solution: 
- contains {{1.000 moles of}} {{potassium permanganate}} 
- {{is saturated}} with {{a lot of solids}}
- concentration {{0.500}} molar
- concentration readout range {{0}} to {{0.500}} molar

### Random change to each slider (high volume & low solute)
Values checked (qual. values) 
Beaker {{nearly full of}} {{a potassium permanganate}} solution. The {{purple}} solution:
- contains {{a low amount of}} {{potassium permanganate}} 
- {{is concentrated}}
- chemical formula of {{potassium permanganate}} is {{KMnO4}}
- concentration readout range {{0}} to {{0.500}} molar 

**Values checked (quant. values) (random change)**
Beaker {{has 0.850 liters of}} {{a potassium permanganate}} solution. The {{purple}} solution:
- contains {{0.195 mol of}} {{potassium permanganate}} 
- concentration {{0.229}} molar
- chemical formula of {{potassium permanganate}} is {{KMnO4}}
- concentration readout range {{0}} to {{0.500}} molar

### Zero solute (pure water)
**Values NOT checked (qual. values)** 
Beaker {{is nearly full of}} {{pure water}}. The {{clear}} solution: 
- contains {{no}} {{potassium permanganate}}
- {{has zero concentration}}
- chemical formula of {{pure water}} is {{H2O}}
- concentration readout range {{0}} to {{0.500}} molar

**Values checked (quant. values)**
Beaker {{has 0.882 liters of}} {{pure water}}. The {{clear}} solution: 
- contains {{0.000}} moles of {{potassium permanganate}} 
- concentration {{0.000}} molar
- chemical formula of {{pure water}} is {{H2O}}
- concentration readout range {{0}} to {{0.500}} molar

**Comment by terracoda** [comment]
@Matthew-phet, in the beaker description in the Play Area, I actually left off the saturation/solids description if the solution is not saturated. Do you think that's ok? It might be nice to use a more explicit short description in the screen summary, and less explicit one here, and see how it goes.

**What do you think?** 

Let me know if I need to update the examples. If all is good as is, please assign to @twant for implementation.

**Comment by Matthew-phet** [comment]
@terracoda yeah that seems like a good idea to me, if you want to update then let me know so i can move it on up the ladder

**Comment by terracoda** [comment]
@Matthew-phet, just for clarity, I am leaving as-is, which is what I think you prefer:
- "is/is not saturated" is described explicitly in summary with only "is saturated" described in Play Area.

In this case, there is no need to update the examples.

**Comment by terracoda** [comment]
@Matthew-phet, back to you to review with @twant.

**Comment by terracoda** [comment]
@twant, nice work so far, and still a little more to do. 
I found some inconsistencies between what's mentioned in the issue comments above and what's been implemented. Here are some screenshots to help iron things out. 

I'll show these to @Matthew-phet today in our meeting and then hopefully you two can do the final implementation and verification of final changes.

I hope these screenshots are helpful.

### Note that I only checked Drink Mix cases
**Page Load - values not checked**
- concentration level will change when that scale is implemented.
- concentration readout item is incorrect in all cases - need to reduce number of digits and add "molar"
<img width="743" alt="drink-mix-page-load" src="https://user-images.githubusercontent.com/1902116/60510316-6a792b80-9ccf-11e9-86d0-7e073aba5557.png">

**Page Load - values checked**
- need to make sure we use correct wording  "mol of" (I think I verified this last week with @Matthew-phet, but I'll check again today) 
<img width="611" alt="drink-mix-values-checked" src="https://user-images.githubusercontent.com/1902116/60510497-d065b300-9ccf-11e9-9b64-a2c9e3a7e16b.png">

**Maxxed/Minned - values not checked**
- no "the" or "The" on "max amount of" solute amount value
<img width="678" alt="drink-mix-maxxed-minned" src="https://user-images.githubusercontent.com/1902116/60510658-3d794880-9cd0-11e9-8df1-deaf1e948009.png">

**Maxxed/Minned - values checked**
<img width="627" alt="drink-mix-maxxed-minned-values-checked" src="https://user-images.githubusercontent.com/1902116/60510758-87fac500-9cd0-11e9-902c-acfc0f31cb8e.png">

**Low Solute and High Volume - values not checked**
<img width="838" alt="drink-mix-low-solute-high-volume-no-values" src="https://user-images.githubusercontent.com/1902116/60510805-a791ed80-9cd0-11e9-9698-86c6343c1678.png">

**Low Solute and High Volume - values  checked**
<img width="814" alt="drink-mix-low-solute-high-volume-values-checked" src="https://user-images.githubusercontent.com/1902116/60510834-b7a9cd00-9cd0-11e9-8ce9-1250e21a6526.png">

**Comment by terracoda** [comment]
Ooops, forgot the zero-solute case...
**Zero drink mix solute - no values**
<img width="812" alt="zero-solute-pure-water-no-values" src="https://user-images.githubusercontent.com/1902116/60511783-153f1900-9cd3-11e9-9064-a946db0c9141.png">
**Zero drink mix solute - with values checked**
<img width="809" alt="zero-solute-values" src="https://user-images.githubusercontent.com/1902116/60511792-196b3680-9cd3-11e9-9bac-c7fe55f4144e.png">

**Comment by terracoda** [comment]
@Matthew-phet, we need to verify "mol of" or "moles of". I see used inconsistent strings when I posted this initial issue comments.

**Comment by terracoda** [comment]
@twant, @Matthew-phet and I verified the proper unit for solute amount is "moles" and "moles of". I'll correct the places above where I made some mistakes.

**Comment by terracoda** [comment]
@Matthew-phet and @twant , I updated the comments above with the new description for the lowest volume amount for the solution. @Matthew-phet like this suggested change in our design meeting today. I'll update #115, too, so things are consistent and clear.
- {{has lowest amount of}} **has been changed to**:
- {{is at lowest amount of}}

**Comment by terracoda** [comment]
I updated the examples above to use "{{is at lowest amount of}}".

Honestly, @Matthew-phet  and @twant, I think we could do without the "is" in both the Play Area Beaker description and the `aria-valuetext` for the solution volume slider, and possibly in the screen summary, too. You would need to verify in #123 for screen summary. Please do what you think is best.

### For example:
**Start of Beaker description:**
"Beaker {{SolutionVolume}} of {{a potassium permanganate}} solution. The {{purple}} solution:"
- "Beaker {{full}} of {{a potassium permanganate}} solution. The {{purple}} solution:"

**`aria-valuetext` for Solution Volume slider:**
"beaker {{SolutionVolume}}"
- {{full}} 
- {{nearly full}} 
- {{over half full}}
- {{half full}}
- {{under half full}}
- {{nearly empty}}
- {{at lowest amount}} 

**Note**: I moved "of" to the base phrase and out of the parameter. I am not sure how things are broken up in the actual sim code.

**Comment by terracoda** [comment]
@Matthew-phet, I think this issue is ready for @twant, so re-assigning. Take it back if you need to. @twant, please reach out with questions if you have any.

**Comment by twant** [comment]
@terracoda thanks so much for your comments on this and many others -- apologies for the delay in responding to them! I'll be working on them this weekend and week to get everything revised, and will reach out with any questions.

**Comment by twant** [comment]
@terracoda @Matthew-phet assigning back over to you for review. The only screenshot that I do not believe has been addressed will be addressed with the revised scale for solution volume.

**Comment by terracoda** [comment]
@twant, this will probably be perfect once the new scales are implemented as well.

**Comment by terracoda** [comment]
@twant, when reviewing today, I noticed some extra "of"'s in the solute amount description (first list item). The amounts that need an "of" have two "of"'s, and the amounts that do not need an "of" have one. The extra "of"'s are not appearing in the Screen Summary, so please do the same thing in the Play Area description. In the A11y View you can see the following:
- max amount of of 
- a lot of of
- a bunch of of
- some of 
- a low amount of of
- a little of
- no of

Description scales for Solute Amount scale #116, Solution Volume #115, and Concentration Level #117, are not yet marked ready for review. Once they are fully implemented, I will need to verify the Beaker's Play Area description again, and I think it will be really good - maybe even perfect - once the scales are implemented.

**Comment by terracoda** [comment]
@twant, I removed the extra "of" in my commit https://github.com/phetsims/molarity/commit/c4843307401f31cecb7d443026096edc5581f3c2 that I forgot to add a comment for, so sorry!

Looks like the extra "of" problem is resolved, though.

**Comment by terracoda** [comment]
Please assign back to us and re-label once new scales are fully implemented.

**Comment by terracoda** [comment]
@twant, I think we are almost there. I'll add some screenshots.

**Comment by terracoda** [comment]
@twant, these are the issues, I am noticing today during my testing:
1. in the concentration readout range, 0.0 should be 0. Apologies for being inconsistent in my examples at the start. Note that 5.0 is correct.
2. "has zero concentration" is showing often when the concentration is not actually at zero. Please make sure that "has zero concentration" only appears when there is no solute. Once there is some solute, concentration has to be at least one concentration level up at "has low concentration".
<img width="509" alt="Screen Shot 2019-07-23 at 12 45 32 PM" src="https://user-images.githubusercontent.com/1902116/61706346-287c5c00-ad48-11e9-91ca-d39716e60a25.png">
<img width="506" alt="Screen Shot 2019-07-23 at 12 55 48 PM" src="https://user-images.githubusercontent.com/1902116/61707105-07b50600-ad4a-11e9-922c-9b6e71e27b40.png">
Same solute position, but with values shown. Solute Amount is 0.35 mol.
<img width="505" alt="Screen Shot 2019-07-23 at 12 55 13 PM" src="https://user-images.githubusercontent.com/1902116/61707118-0c79ba00-ad4a-11e9-87cb-27b040972ba5.png">
<img width="658" alt="Screen Shot 2019-07-23 at 1 04 08 PM" src="https://user-images.githubusercontent.com/1902116/61707332-85791180-ad4a-11e9-9dfb-238e3bfffc8f.png">

3. capitalization is looking good. I just found "Is saturated..." that should be "is saturated"
<img width="512" alt="Screen Shot 2019-07-23 at 12 49 39 PM" src="https://user-images.githubusercontent.com/1902116/61706543-a0e31d00-ad48-11e9-9a56-099affc636c9.png">

**Comment by terracoda** [comment]
@twant, in addtion to the three issues above:
4. with Solution Values checked, we are missing "of", after "moles". Apologies, if I was the one who messed it up. I know I removed an "of" in a previous commit. In fact, this bullet sounds fine without an "of", so if it's easier to leave it off with Solution Values checked, that's okay with me.
<img width="653" alt="Screen Shot 2019-07-23 at 1 16 37 PM" src="https://user-images.githubusercontent.com/1902116/61708128-4ea3fb00-ad4c-11e9-8860-fac3bbfdc60a.png">

5. when Solution Values are checked, the values for solution are still qualitatitive. This is good in the screen summary, but here on the actual Beaker in Play Area, I think it's best to provide the raw values...that said, can you check with @Matthew-phet on this point. My examples have raw values, but I may have made a mistake.
... more to come

**Comment by terracoda** [comment]
@twant, I think the main issue is issue is item 2, the range for "has zero concentration" has to be change to a single value, as I mentioned in #117. 

@Matthew-phet, could you verify what values you want for solute amount and concentration level for item 5 - qualitative descriptions or quantitative values when solutions?

Assigning back over to you folks.

**Comment by terracoda** [comment]
Wrong screen shot for item 5. I will replace. it.

**Comment by terracoda** [comment]
<img width="725" alt="Screen Shot 2019-07-23 at 5 29 32 PM" src="https://user-images.githubusercontent.com/1902116/61725155-8cfee180-ad6f-11e9-8056-32196ddb5ff3.png">

**Comment by terracoda** [comment]
@twant, could you make the value for concentration quantitative, please.

**Comment by terracoda** [comment]
@twant, apologies for my confusion here. @Matthew-phet and i discussed this, and we would like the description of concentration to be quantitative (like in the example at the beginning) when Solution Values are checked.

**Comment by twant** [comment]
Bullet about concentration for no solute case: 
Qual: "has no solute."
Quan: "has zero moles of solute."

**Comment by terracoda** [comment]
@twant, to summarize the remaining 5 minor items for this issue are:
1. in concentration readout range "0.0" should be "0"
2. the zero-level of concentration "has zero concentration" needs to be restricted to 0.000 molar, or 0.000 moles of solute. It has to have a single value range.
3. no capitalization on saturation line item
4. no "of" in "of moles" (OPTIONAL)
5. with values checked, want quantitative value for the concentration item

**Comment by twant** [comment]
@terracoda @Matthew-phet pushed to master, will be in tonight's dev version for review.

**Comment by terracoda** [comment]
@twant, I still get "has zero concentration" when the Solute Amount is 0.001 and concentration readout is 0.005 molar.

**Comment by terracoda** [comment]
**Adding screen shots for visual understanding:**
<img width="805" alt="PA_Beaker_pp_values_checked" src="https://user-images.githubusercontent.com/1902116/62801220-1d406480-ba9a-11e9-995a-c6017847113c.png">
<img width="792" alt="PA_Beaker_pp_values_hidden" src="https://user-images.githubusercontent.com/1902116/62801222-1e719180-ba9a-11e9-8ef6-b3a73c41fed6.png">

To clarify this issue, I think the main issue is that we get the description relevant to zero solute/zero concentration when the solute is not actually zero and concentration is not actually zero.

@twant, could you tweak whatever necessary to make sure no solute and zero concentration are restricted to a value of 0.000 moles and 0.000 molar.

Assigning back to you. Any questions?

**Comment by twant** [comment]
pushed an adjustment to master, @terracoda! Assigning back to you two.

**Comment by terracoda** [comment]
Looks good! I think you got it! I tested with the Shift modifier, and it seems to be working great.
<img width="859" alt="Screen Shot 2019-08-11 at 2 42 00 PM" src="https://user-images.githubusercontent.com/1902116/62839891-50bff200-bc46-11e9-8a66-d4bebc20af29.png">
<img width="869" alt="Screen Shot 2019-08-11 at 2 41 15 PM" src="https://user-images.githubusercontent.com/1902116/62839893-5289b580-bc46-11e9-994b-bfbceec80641.png">

I am ready to close this one if @Matthew-phet is. Over to you @Matthew-phet.
