### ISSUE TITLE
New Responsible dev

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/molarity#124]
@pixelzoom is fairly overloaded with sims for which he is responsible dev, this sim is now getting lots of work and he has requested a new responsible dev be identified.

@twant I think you will be a natural choice if the time comes that you are with the project full time, but for the moment I think @zepumph or @jbphet we be the appropriate person.

If either @zepumph or @jbphet wishes to volunteer, please adjust the responsible dev document and put yourself there. If not, lets discuss next time I am in town.

**Comment by zepumph** [comment]
I am happy to take this on. I have been in the sim recently because of PhET-iO (about a year ago), and a11y stuff with @twant this spring. @jbphet I see you have twice as many sims you are responsible for than I. That said let me know if you want this one.

**Comment by jbphet** [comment]
Thanks @zepumph - I appreciate it.
