### ISSUE TITLE
Change Solute alert: legacy alert fires sometimes

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#129]
This incorrect legacy alert (circled in red in screenshot) might be resolved by work in #127.

I just wanted to document the issue here as I did see the alert pop up in testing master yesterday.

This alert seems to pop up in a few places, especially before a solute change results in a saturated solution.

Testing from master (phetmarks). It pops up now when:
- the solute amount is zero, and you change the solute in beaker
- when a change a solute and the solution goes from unsaturated to unsaturated (no change in saturation)

Once you hit a saturated solution with a solute change, it seems to pop up less.

Here's a screenshot from master (today).
<img width="369" alt="Screen Shot 2019-07-03 at 1 57 30 PM" src="https://user-images.githubusercontent.com/1902116/60589934-fefc9000-9d9a-11e9-8f56-c8b98bab3386.png">

**Comment by terracoda** [comment]
@twant, as I said this bug might be resolved by work in #127, because as of yesterday there was no specific alert for when there was a change of solute with the solute amount at zero moles. #127 provides those missing alerts.

Let me or @Matthew-phet know if you have any questions.

**Comment by twant** [comment]
@terracoda just pushed some changes for #127 -- let me know if they also fix this bug!

**Comment by terracoda** [comment]
@twant, the combobox is now not working with the keyboard?? I can't navigate with the arrow keys through the list. I'll open an issue for that. 

However, that said, while I was testing yesterday, I did not see this bug in the A11y View, and using it now with the mouse I do not see the old alert.

I have a feeling it's fixed. I'll close for now and re-open if the alert pops-up in later testing.
