### ISSUE TITLE
Add accessibility to the sim constructor.

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#131]
I think we are at the point where we can turn Molarity on by default on sim startup. This involves passing the `accessibility` boolean option into the `Sim` constructor in molarity-main. @twant give it a go, and let me know how it does.

**Comment by twant** [comment]
@zepumph I think I've done this successfully (when I preview in require.js mode without an a11y query parameter I am able to access the descriptions with a screen reader!). I do notice that the descriptions are read so loudly that they tend to drown out the sound effects. Have you noticed this with other sims?
