### ISSUE TITLE
Changed original string key -- how to handle? 

### ISSUE THREAD

**Issue by twant** [phetsims/molarity#142]
@jbphet, I made a change to the "show values checkbox" string key a while ago because we changed the name to be "solution values checkbox" instead. However, @zepumph pointed out that this will be a problem for translation. How would you like me to handle this? Happy to revert back to the original string key, or implement any other changes you think are necessary for translation! 

Additionally, I added an item to the Internationalization of the code review checklist specifically to look for changes to string keys that may affect translation. I added to check with you about issues like this in the future -- is this okay with you?

**Comment by jbphet** [comment]
> How would you like me to handle this? Happy to revert back to the original string key, or implement any other changes you think are necessary for translation!

Reverting back to the original string key is the best approach.  I just checked, and there are 45 translations for the existing string key, all of which would break (meaning that this particular string would no longer be translated in their version of the sim) if the sim is published with a different string key.  Changing the value is fine.

> Additionally, I added an item to the Internationalization of the code review checklist specifically to look for changes to string keys that may affect translation. I added to check with you about issues like this in the future -- is this okay with you?

Yes, that's okay with me.  The translation utility was a sort of low budget project, and it serves us well for the most part, but it is far from bulletproof.  Someday I hope to spend enough time to make it robust enough to handle situations like this, but that day isn't today.  Letting people know to check in with me on such questions is probably the best way to do things for now.

**Comment by twant** [comment]
Thanks for your advice, @jbphet! I've reverted back to the original key, but kept the value as the changed one.
