### ISSUE TITLE
Remove period on list item for Chemical formula

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#145]
This is an easy one @twant. I just notice that there is a lonely period on the list of items describing the solution in the beaker. Please remove the period at the end the line item describing the chemical formula. 

And I trust you can verify this issue yourself. so go ahead and close when you are done.

![remove-period](https://user-images.githubusercontent.com/1902116/65631953-2ab29f00-dfb3-11e9-9a38-9cd887b7291f.png)

When the beaker has water, there is no period, so that string is fine as-is.
![Screen Shot 2019-09-25 at 4 42 45 PM](https://user-images.githubusercontent.com/1902116/65632145-909f2680-dfb3-11e9-9276-e39f1709e44d.png)

**Comment by twant** [comment]
Thanks for catching this, @terracoda! Fixed and closing.
