### ISSUE TITLE
Add space in context responses (alert strings) that include the amount of solids.

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#146]
@twant, we need a space in the alert strings that add the amount of solids to increased or decreasing concentration. 
![Screen Shot 2019-09-25 at 3 25 26 PM](https://user-images.githubusercontent.com/1902116/65632528-76b21380-dfb4-11e9-83a6-9ad0469ab1d9.png)

**Comment by twant** [comment]
Fixed and closing!
