### ISSUE TITLE
Tweak so "a couple of solids" appear in context responses (alerts)

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#148]
@Matthew-phet, I played with Molarity today and I think everything is looking pretty good.

I noticed that "a couple of solids" rarely or never shows up while increasing concentration, though it shows up while decreasing concentration.

I'm wondering if you want to tweak that, so "a couple of solids" is announced at least once when that state is true.

In screenshot below, it goes from solids appear to a few solids a couple of alerts later.
![Screen Shot 2019-09-25 at 3 26 57 PM](https://user-images.githubusercontent.com/1902116/65635278-98ae9480-dfba-11e9-993e-b70ad04fddfa.png)

**Comment by terracoda** [comment]
I'm thinking you might want something like this:
- Solution saturated. Beyond max concentration solids appear.
- More solute, more solids. Still saturated with a couple of solids.
- More solute, more solids. (a couple of times)
- More solute, more solids. Still saturated with a few of solids.
- More solute, more solids. (a few times)
- More solute, more solids. Still saturated with some solids.
- More solute, more solids. (a few times)
- More solute, more solids. Still saturated with a bunch of solids.
- More solute, more solids. (a few times)
- More solute, more solids. Still saturated with a lot of solids.

**Comment by Matthew-phet** [comment]
yeah this seems like a good change! Should i assign taylor or do we need to add more info first?

**Comment by Matthew-phet** [comment]
@twant We mainly want to see a "More solute, more solids. Still saturated with a couple of solids." to come right after "Solution saturated. Beyond max concentration solids appear."

**Comment by terracoda** [comment]
@twant, of course the description of the amount of solids has to be true in the model. I'm not sure if any of the solutions can go from "not saturated" to "saturated with a few solids" in one key press. If that's possible that's fine. We just don't want the range for "a couple of solids" to be skipped.

**Comment by twant** [comment]
@terracoda @Matthew-phet just pushed an update. It definitely varies quite a bit with the solute chosen, but I do think it's better than before. Let me know what you think!

**Comment by terracoda** [comment]
@twant, I see "a couple of solids" show up now in both directions. Thanks!
I agree that all this is quite tricky as the molar and solids vary so much between different solutions.

@Matthew-phet, please have a look and close if this alerts are good from your perspective.

**Comment by Matthew-phet** [comment]
Looks good to me! Closing.
