### ISSUE TITLE
Seems like there are two steps on for "No solute" sometimes

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#150]
@twant and @Matthew-phet, it is pretty consistent (but not 100%) that I get "no solute" and ("0.000 moles") twice at the end of the Solute Amount slider.

The first time, I get "no solute" when hitting the bottom of the Solute Amount slider, the slider value (object response) is followed by the alert (context response) "Less solute, less concentrated. Solution has zero concentration."

Then I press down arrow again, and I get "no solute" a second time, and the alert (context response) is, "No solute. Solution is pure water." 

**Step before actual last step - value "no solute"**
Note the sound is correct. I get the nice big boouump sound.
![zero-solute-but-not-yet-water?](https://user-images.githubusercontent.com/1902116/65787793-514c1380-e134-11e9-9270-57be4b6175db.png)

**Then there is one more possible step, and again the value is "no solute"**
Note the sound is seems chopped off, but I do get some sound.
![zero-solute-pure-water](https://user-images.githubusercontent.com/1902116/65787822-5dd06c00-e134-11e9-9321-c4c44dc16a56.png)

The same thing seems to happen with Solution Values checked:
**Step before actual last step - value "0.000 moles"**
<img width="710" alt="Screen Shot 2019-09-27 at 2 36 01 PM" src="https://user-images.githubusercontent.com/1902116/65787869-7b9dd100-e134-11e9-9c83-00b933f6954f.png">

**Then there is one more possible step, and again the value is "0.000 moles"**
<img width="708" alt="Screen Shot 2019-09-27 at 2 36 19 PM" src="https://user-images.githubusercontent.com/1902116/65787880-8193b200-e134-11e9-96ea-56185e7ced8e.png">

I am not sure if this could be a rounding error, but @twant could you make sure there is only 1 position for "no solute" and only one position for "0.000 moles" and also make sure the alert that fires right after that value is "No solute. Solution is pure water." It is the same alert for both Solution Values checked and not checked.

**Comment by terracoda** [comment]
And while you are in there, please add a period to the end of the alert, "No solute. Solution is pure water."

**Comment by twant** [comment]
@terracoda looks like this was a rounding error. Thanks for catching it! I believe it's been fixed. Assigning back over to you for review.

**Comment by terracoda** [comment]
Awesome! I had a quick review with the A11y view. It looks good to me!

**Comment by terracoda** [comment]
Is it safe to close, @twant?

**Comment by terracoda** [comment]
It's assigned to me, so I'll assume I can close ;-)
