### ISSUE TITLE
Resize Pointer Areas

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#151]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/436.  Quite minor, but may still be worth looking at if it is a quick fix.
Since the wording of the "Show Values" checkbox changed to "Solution Values" the red touch area cuts through the end of the word.  In practice this is unlikely to cause problems, but documenting and bringing to attention just in case.

**Visuals**
![cutoffarea](https://user-images.githubusercontent.com/41024075/66500630-1c6a8580-ea7f-11e9-869e-5ec80c11661f.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molarity‬
URL: https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.23/phet/molarity_en_phet.html?showPointerAreas
Version: 1.5.0-dev.23 2019-10-04 22:27:51 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Note: Could be more noticeable with longer translations

**Comment by twant** [comment]
Just adjusted the pointer area to make it a little larger. @zepumph I just added 5 to the touchArea width of the checkbox -- can you verify that this isn't likely to break anything else?

**Comment by KatieWoe** [comment]
Just thought to check with longer strings, and it seems to be a problem there.  Does occur in published version.
![problemdouble](https://user-images.githubusercontent.com/41024075/66776698-37286a00-ee84-11e9-8f42-7fac075771c2.png)

**Comment by ariel-phet** [comment]
@KatieWoe @twant @zepumph the idea of the touch area extending is to increase usability. I think using the size of the English string is a totally reasonable proxy. We want a situation where if a user "aims" for the check box, they basically get the checkbox. I don't think it is at all necessary to extend the pointer area dynamically based on the locale or such.

I think this issue can be closed.
