### ISSUE TITLE
Sim doesn't load on IE

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#153]
For https://github.com/phetsims/QA/issues/436. Not in published version.
The sim does not load past a small fraction of the loading bar in IE.  This console error appears:
![error](https://user-images.githubusercontent.com/41024075/66503179-f85d7300-ea83-11e9-92b6-a1d063cf2732.png)

**Comment by twant** [comment]
Tried replacing `.includes` with `.indexOf` to see if this fixes the IE issues. Will create a new dev version and test on IE soon!

**Comment by twant** [comment]
Okay, I just tested a new dev version on IE and it loads with that change made. @KatieWoe this is my first time going through QA processes, so I'm not quite sure how to proceed -- apologies! Would you like me to assign these back over to you as they are resolved, or create a new dev test issue once all of the issues are resolved?

The dev version with this fix is 1.5.24

**Comment by KatieWoe** [comment]
Generally for dev tests we check them as they are fixed on master, and for rc tests they are put in the "issues to check" section of the next rc test and we test them then.

**Comment by KatieWoe** [comment]
However, getting master to open in IE can be a bit of a pain, so a separate dev version could be useful in this case. It would be up to your discretion and what kind of testing would be more useful for you.

**Comment by twant** [comment]
@KatieWoe thanks for the advice! At this point, it would be really helpful if you're able to test the most recent dev version (1.5.0-dev.24) to verify that this issue is fixed. I tested in a virtual machine, but I don't have IE installed on my machine and I want to be sure it's fixed. Thanks for your help with this!

**Comment by KatieWoe** [comment]
Checked the mentioned dev version on Win 10 IE and it seemed to open just fine.

**Comment by twant** [comment]
Thanks, @KatieWoe! Closing this issue.
