### ISSUE TITLE
Sound design: Concentration & Precipate Sounds

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#159]
Last week I had 2 remote sessions to assess the design (description and sound) for Molarity one with a consultant and one with a university student.

I need to add some more details from notes and recordings, but both participants had some trouble with the sound representing concentration. In addition, @KatieWoe in QA had concerns about the the changing direction of tones after saturation happens and the sound switches to aligning with the presence of the precipitate.

The current sounds:
1. Concentration:
- sound becomes higher in tone/pitch as solution becomes more concentrated
- sound becomes lower in tone/pitch as solution becomes less concentrated
a. What this means for **Solute Amount** slider:
- increase in Solute Amount (more concentrated) -> higher tone/pitch
- decrease in Solute Amount (less concentrated) -> lower tone/pitch (lowest tone = no solute)
b. What this means for **Solution Volume** slider:
- increase in Solution Volume -> lower tone/pitch
- decrease in Solution Volume -> higher tone/pitch
2. Precipitate sound:
- tinkle sound becomes lower in tone/pitch as more solids appear (concentration fixed)
- tinkle sound becomes higher in tone/pitch as solids disappear (concentration fixed)
a. Solute Amount - increase = lower tone (more solids); decrease = higher tone (less solids)
b. Solution Volume - increase = higher tone (less solids); decrease = lower tone (more solids)

**Need to verify with my notes the following**
- Our consultant did not map the sound to concentration and found it strange that the sound for Solute Amount was going down in tone when the amount was decreasing, and that the sound for Solution Volume did the opposite.
- Student mapped the sound to concentration, but was still somewhat confused by the tone.

**Comment by emily-phet** [comment]
Notes from investigating this further:
- From Feb. 12 2019 notes (I added emphasis):

>  John will apply an algorithm for selecting playback rate of sounds, and have it go **lower** for greater concentrations. 

- From Feb. 19 2019
Looks like the first working version of the [sim with sound](https://phet-dev.colorado.edu/html/phet-io-wrapper-sonification/1.0.0-dev.99/phet-io-wrapper-sonification/molarity/html/molarity-sonification.html?accessibility) had high to low concentration mapped as low to high tone (as it is currently). 

- Later, [Wrapper 102](https://bayes.colorado.edu/dev/html/phet-io-wrapper-sonification/1.0.0-dev.102/phet-io-wrapper-sonification/sonification.html) has the first Molarity options version with different sounds for the concentration - none with reverse mapping. 

- Looking through to Wrapper 111 (April 2019) still none that shift the mapping. 

I think we probably discussed inverting the mapping, but perhaps never saw a working version. 

@Ashton-Morris  @jbphet @terracoda Based on this, and potential issues brought up from interviews, I think we should make a version with the concentration sound mapping inverted from the current version. 

@Ashton-Morris @jbphet - If it, as you're creating this new version, if the mapping feels off to you give me a heads up. I'm not sure if it will 'feel wrong' or just 'feel different'. If it "feels wrong" to us, we should ask for some quick feedback from others on the team not as closely connected as we are. If it 'feels wrong' to others on the team as well we should stop work on the new variation.

**Comment by terracoda** [comment]
I'm really curious about what a reverse mapping would sound like, so I am glad we are exploring this. I don't think I was deeply involved in earlier versions. The options do not sound familiar.

**Comment by jbphet** [comment]
Sounds like a plan.  Our point of reference for the mapping against which we will compare the changes should be the [current dev version 1.5.0-dev.24](https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.24/phet/molarity_en_phet.html). I'll invert the mapping for concentration and leave the mapping for precipitate as is and will publish a new dev version for us to review.  

@twant and @zepumph - I know you've both been involved with moving this sim towards publication, so I'm tagging you so that you're aware of this.

**Comment by jbphet** [comment]
I made a quick revision to see if this gets us in the ballpark.  @terracoda, @Ashton-Morris, and @emily-phet - please try out this revision and see if you think this is an improvement?  If so, we can hammer out the details of exactly what range of pitches should be used at the next sound design meeting.

https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.25/phet/molarity_en_phet.html

**Comment by terracoda** [comment]
@jbphet, I hear a deep bong sound (sometimes and somewhat consistently) at the bottom of the Solute Amount Slider. Is that intended to indicate water? Is that a bug?

**Comment by terracoda** [comment]
@jbphet, I think the low-ish sound I am getting at the bottom of the Solute Slider is the same as "no solute - water sound" on the Solution Volume slider once the solute is zero. And since I only hear the sound after I hit zero solute, I do think it is a bug.

I am using Safari and Firefox on MasOS 10.13.6

**Comment by terracoda** [comment]
Other than that bug, I think the sounds are sounding quite nice with the inverted mapping. We don't have the nice low water bong sound anymore, but the high tone at water is still quite distinct. And I do like the transition from not saturated to saturated and back again.

**Comment by jbphet** [comment]
@terracoda - good catch, I'd missed the case where the solution volume was changing with no solute present.  That case should be fixed now, the latest is in https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.26/phet/molarity_en_phet.html.

**Comment by jbphet** [comment]
We reviewed this in the 10/22/2019 sound design meeting.  For the most part, we like this new mapping, though the deep "bonk" sound that was previously used for no solute is missed.  We should increase the volume of the new "tink" sound that indicates no solute.

We're going to move forward with the reversed mapping of the concentration sound, i.e. lower pitched bonks means more solute.

**Comment by jbphet** [comment]
> We should increase the volume of the new "tink" sound that indicates no solute.

I've done that now.  We should review and decide if we are done with this set of changes.

**Comment by terracoda** [comment]
I miss the bonk, too, but I think the mapping is better, in general.

**Comment by terracoda** [comment]
@Matthew-phet, please have a listen to the remapped concentration sound. Lin is in https://github.com/phetsims/molarity/issues/159#issuecomment-544726601

Would love to hear your comments.

**Comment by Matthew-phet** [comment]
Yup! mapping sounds good to me

**Comment by jbphet** [comment]
Sounds like we have a quorum.  @emily-phet also said via Slack, "[L]ooks like everyone is a go with the new concentration sound."  I'll close this issue and we will move forward with the publication when the rest of the sim is ready.
