### ISSUE TITLE
Update Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molarity#161]
#154 revealed that it's possible for a solution to be at the saturation point without the "Saturated" text or any visible precipitate. Discussion is still ongoing about how this will be addressed.

Regardless of the outcome, it would be good to add something about this to the Teacher Tips, but I'll wait until #154 is concluded to make any changes.

**Comment by twant** [comment]
Now that #154 has been resolved, how do you want to handle this as we prepare the sim for a11y publication, @arouinfar?

**Comment by arouinfar** [comment]
@twant I'll update the teacher tips and upload it to the site once the sim redeploys. There's nothing that needs to be done on your end for this. Thanks for check in!

**Comment by twant** [comment]
Thanks @arouinfar!

**Comment by arouinfar** [comment]
Updated teacher tips are ready and awaiting redeploy.

**Comment by arouinfar** [comment]
Updated tips have been uploaded to the site.
