### ISSUE TITLE
Heard "no solute" with "low concentration"

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#164]
@twant, with Gold (III) chloride and the shift key I hit the region "no solute" before the end of the slider.
<img width="876" alt="no-solute-region-too-soon" src="https://user-images.githubusercontent.com/1902116/68130951-d1655600-fef6-11e9-9865-82a1c0843f25.png">

This might be a rounding error; just making note of it as something to check as soon as we finish #160 and #154 .

**Comment by twant** [comment]
Just tested this again with a few different settings (and all of the solutes) and wasn't able to reproduce. Have you seen this since, @terracoda?

**Comment by terracoda** [comment]
@twant, maybe it was a glitch, or maybe it's been fixed by some other thing.
I also haven't heard this happen since I posted the issue.
Let's close for now and re-open if it pops up again.
