### ISSUE TITLE
Change H3 "Solution Controls" to "Beaker Solution Controls"

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#166]
Apologies @twant for not making an issue for this minor change a long time ago. @Matthew-phet and I discussed making this change after the last interview but forgot to make an issue for it.

In our last interview with this sim, the user had a great exploration of the sim, but only read the full description of the beaker once. When they discovered the updated description of the Beaker during the interview questions they realized there was a lot of nice detail they had not come back to.

I suggested to @Matthew-phet that we change the heading identifying the "Solution Controls" to "Beaker Solution Controls" to help cue that when making changes to the solution, they are indeed making changes to the solution in the beaker.

**Comment by twant** [comment]
@terracoda @Matthew-phet just pushed these changes. Assigning over to you for review!

**Comment by terracoda** [comment]
Great @twant, Thanks! Marking as resolved.
