### ISSUE TITLE
Vertical slider thumb stops showing enabled state

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molarity#17]
After furious amounts of double-clicking the track (not the thumb itself) and sliding along it, the thumbs can eventually stop highlighting on mouse-over.

https://drive.google.com/file/d/0B3HJopSo_QqLSnBnb2pyRnU5NFE/view?usp=sharing

So far seems to be Chrome specific, but I may not have spent enough time on the other browsers. Tested on Win 7 and 8.1.

Troubleshooting information:
Name: Molarity
URL: http://www.colorado.edu/physics/phet/dev/html/molarity/1.1.0/molarity_en.html
Version: 1.1.0
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
Language: en-us
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by pixelzoom** [comment]
Closing. This is a general issue that affects sliders in all sims, being tracked in https://github.com/phetsims/sun/issues/155.
