### ISSUE TITLE
MolarityBeakerDescriptionNode can be the description list

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#170]
I noticed that is just a container Node, but the `MolarityBeakerDescriptionNode` itself doesn't have any PDOM content. Perhaps try getting rid of `beakerDescriptionList` in exchange for calls to `this` instead.

**Comment by twant** [comment]
Thanks for these suggestions! I just implemented and pushed these changes. Do you want to review to confirm that these are changed as you'd imagined @zepumph?

**Comment by zepumph** [comment]
Your changes look good. Closing
