### ISSUE TITLE
ConcentrationDescriber.js Review 

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#171]

**Comment by zepumph** [comment]
https://github.com/phetsims/molarity/issues/165

**Comment by zepumph** [comment]
- [ ] There is `SOLIDS_STRINGS_LOWERCASE`, but some of SOLIDS_STRINGS are lowercase also. Can you explain why only some of them are capitalized?

**Comment by zepumph** [comment]
Today I got to `getCurrentSaturatedConcentration`, @twant feel free to start working on it if you would like.

**Comment by zepumph** [comment]
I'm going to move on to another file now.

**Comment by twant** [comment]
@zepumph agree about hasSolute(). Just moved it to Solution.js (and adjusted the logic to match what is in getColor().

**Comment by twant** [comment]
For `getCurrentConcentrationRangeClause`, I changed the variable name to "displayedMaxConcentration" and added a comment explaining why it is clamped.

**Comment by twant** [comment]
@zepumph saw the typedef you added for what is now called getChangeStrings. I added in a couple of sentences describing the type, and added the typedef and updated doc for SoluteAmountDescriber and VolumeDescriber. Assigning this whole issue over to you for review.

**Comment by zepumph** [comment]
- [ ] @twant please revert https://github.com/phetsims/molarity/commit/0eb710e225858e1722e215f86bde07627f8ad530 if you don't like it. I thought it a bit clearer to know that both begin as blank strings, and opt in to content given the right conditionals.

**Comment by zepumph** [comment]
>@zepumph saw the typedef you added for what is now called getChangeStrings. I added in a couple of sentences describing the type, and added the typedef and updated doc for SoluteAmountDescriber and VolumeDescriber.

Instead of duplicating the doc, I just moved it to the alert manager, since that is really where it belongs. For example if a third slider/describer was added, then it would need to adhere to the same api to work with the alert manager. I also renamed it to something "slider" specific, since it was at least better than `ChangeStrings`, note sure it is the best name though.

I also created https://github.com/phetsims/molarity/issues/191 and made notes to discuss a few other issues with you this evening. 


Please review my above commits and close if all is well.

**Comment by twant** [comment]
Looks good! Thanks @zepumph! Closing.
