### ISSUE TITLE
Region strings should be unique

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#172]
While working on https://github.com/phetsims/molarity/issues/171, I saw that `ConcentrationDescriber` has a region set called `SOLIDS_STRINGS`, and `SoluteAmountDescriber` has a region set called `SOLUTE_AMOUNT_STRINGS`. Both of these region sets has the same "some" string in it. This makes the assumption that in all languages, that region both of those sets can be described with the same word. We don't want to make that assumption. It is similar to the reason why we don't factor out a string like `the: {value: 'the'}` and fill it in whenever we want to say "the". 

It may make more sense if you think of strings as hierarchical. For example, an object per region set:

```js

    soluteAmount: {

      // Solute Amount Regions - uppercase
      maxAmountOf: {
        value: 'Max amount of'
      },
      aLotOf: {
        value: 'A lot of'
      },
      aBunchOf: {
        value: 'A bunch of'
      },
      some: {
        value: 'Some'
      },
      aLowAmountOf: {
        value: 'A low amount of'
      },
      aLittle: {
        value: 'A little'
      },
      no: {
        value: 'No'
      }
    },

    solidsAmount: {
      aLotOf: {
        value: 'A lot of'
      },
      aBunchOf: {
        value: 'A bunch of'
      },
      some: {
        value: 'Some'
      },
      aCoupleOf: {
        value: 'a couple of'
      },
      aFew: {
        value: 'a few'
      }
    },
```

The above is likely not exactly right, but this direction will be the most clear long term, and best for i18n.

**Comment by twant** [comment]
Changed solids regions strings, next steps are to update organization of region descriptions for other describers.

**Comment by twant** [comment]
@zepumph I reorganized the region strings so that they're all grouped by property. I added some additional organizing structures (like nesting capitalized and lowercase options), which I think mirror the StringCasingPair type you implemented (which I like a lot) from #174. Assigning over to you to review

**Comment by zepumph** [comment]
Thinking about being future proof, soon these strings will not be stored in MolarityA11yStrings, but instead directly in the json strings file. When that occurs, they will be susceptible to a lint rule that requires the string key and the variable name to match. So for example:

`  const redCapitalizedString = MolarityA11yStrings.soluteColors.capitalized.red.value;`

This doesn't fail now, but when it is converted to use the `string` requirejs plugin like:
`const redCapitalizedString = require( 'string!MOLARITY/a11y.soluteColors.capitalized.red.value' );

The lint rule will require the left hand var to be `soluteColorsCapitalizedRedString`. So all of these must be changed, whether it is now, or while working on https://github.com/phetsims/chipper/issues/795. Could you go through and try to name them like so? This will help greatly in the future conversion. Thanks!

A few pieces to note about the var naming conventions:
* suffixed with `String`
* don't include the `a11y` prefix
* see temporary a11y string naming guidlines in https://github.com/phetsims/phet-info/blob/master/doc/how-to-add-accessible-interactive-descriptions-to-a-sim.md#handling-a11y-specific-strings as a review.

**Comment by zepumph** [comment]
Also note that before I commented above, I wrote out https://github.com/phetsims/chipper/issues/826, and decided keeping this convention was better than changing the lint rule.

**Comment by twant** [comment]
@zepumph updated all of the variable names! Good to close?

**Comment by zepumph** [comment]
Excellent!
