### ISSUE TITLE
ConcentrationDescriber `*ToIndex` functions should be implemented with a loop or `LinearFunction`.

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#173]
Unlike other places where the regions are mapped non-linearly, these regions (save the edge single value regions) are linearly spaced. Instead of using the duplicative format for other cases, (the one I recommended using in situations like `soluteAmountToIndex`), let's use a for loop or a `LinearFunction`.

I think a loop would be the simplest, but also you could look into creating a `LinearFunction` for each new maxConcentration, and then using that to calculate the middle regions. And for extra credit, if you were worried about memory, you could keep a map of all the linear functions created so far based on the maxConcentration, since there are only N of those (where n is the number of solutes).

from https://github.com/phetsims/molarity/issues/171 

Let me know if this doesn't make sense.

**Comment by twant** [comment]
@zepumph just pushed changes, although may want to hold off on reviewing/closing this one until I take a look at the other describers!

**Comment by zepumph** [comment]
Above I committed a potential simplification to the solids loop. I wasn't understanding why we were subtracting values, and I also felt like it was strange to go from zero to the length. I tested and found that it was working as I was expecting it to, with even ranges of solids for Potassium permanganate from saturated to min vol max solute amount.

For the concentrationToIndex I was a bit more confused, enough so that I didn't want to commit anything before discussing.

We even regions save two single value regions (for min and max). I wasn't sure why there was so much added complexity, can't we just test those two regions, and then otherwise treat it the same as solids amount? Why do we need to subtract a hard coded value?

How does this look to you?
```diff
Index: js/molarity/view/describers/ConcentrationDescriber.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/molarity/view/describers/ConcentrationDescriber.js	(revision bc98c2794df2b26ea464c4666458911bdcab80ca)
+++ js/molarity/view/describers/ConcentrationDescriber.js	(date 1575929106522)
@@ -468,12 +468,15 @@
     const scaleIncrement = maxConcentration / ( CONCENTRATION_STRINGS.length - 2 );
     const concentrationRounded = Util.toFixed( concentration, MolarityConstants.CONCENTRATION_DECIMAL_PLACES );
 
-    if ( concentrationRounded > maxConcentration - .001 ) {
+    if ( concentration === maxConcentration ) {
       return CONCENTRATION_STRINGS.length - 1;
     }
+    else if ( concentration === 0 ) {
+      return 0;
+    }
     else {
       for ( let i = 0; i < CONCENTRATION_STRINGS.length - 1; i++ ) {
-        if ( concentrationRounded <= scaleIncrement * i - .001 ) {
+        if ( concentrationRounded <= ( i + 1 ) * scaleIncrement ) {
           return i;
         }
       }

**Comment by zepumph** [comment]
@twant and I worked on this, I'll give a spot check before closing.

**Comment by zepumph** [comment]
All looks good. Closing
