### ISSUE TITLE
Make sure all a11y string keys are perfect

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#178]
From #165, I have found that it is really nice to audit the a11y string key names once the design has stopped iteration. This can help organization because many strings end up changing quite a bit from when they were originally created.

For example, `stateOfSimInteractionHintString` to me feels like it maybe used to be dynamic since it also is prefixed with `stateOfSim`, but it may be nicer if named parallel to the other static screen summary strings, like `screenSummaryInteractionHintString`.

Often to do this I just look at the a11y strings file, and try to follow the criteria outlined in the code review checklist (like you likely have already done!):

>- [ ] Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published. Guidelines for string keys are:
  
>  (1) Strings keys should generally match their values. E.g.:
  
  ```js
  "helloWorld": {
    value: "Hello World!"
  },
  "quadraticTerms": {
    value: "Quadratic Terms"
  }
  ```
  
>  (2) If a string key would be exceptionally long, use a key name that is an abbreviated form of the string value, or that captures the purpose/essence of the value. E.g.:
  
  ```js
  // key is abbreviated
  "iWentToTheStore": {
    value: "I went to the store to get milk, eggs, butter, and sugar."
  },
  
  // key is based on purpose
  "describeTheScreen": {
    value: "The Play Area is a small room. The Control Panel has buttons, a checkbox, and radio buttons to change conditions in the room."
  }
  ```
>  (3) If string key names would collide, use your judgment to disambiguate. E.g.:
  
  ```js
  "simplifyTitle": {
     value: "Simplify!"
  },
  "simplifyCheckbox": {
     value: "simplify"
  }
  ```
  
>  (4) String keys for screen names should have the general form `"screen.{{screenName}}"`. E.g.:
  
  ```js
    "screen.explore": {
      "value": "Explore"
    },
  ```
  
>  (5) String patterns that contain placeholders (e.g. `"My name is {{first}} {{last}}"`) should use keys that are unlikely to conflict with strings that might be needed in the future.  For example, for `"{{price}}"` consider using key `"pricePattern"` instead of `"price"`, if you think there might be a future need for a `"price"` string.

I haven't really looked at any others, but feel like you probably know better if the are appropriately named at this point.

**Comment by twant** [comment]
Checked and changed some to try to label more clearly! Would you like to review before closing, @zepumph?

**Comment by zepumph** [comment]
That's awesome, thanks!
