### ISSUE TITLE
capititalized/lowercase string naming convention

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#179]
In this sim there are many spots where we need both the lowercase version of a string, and a captialized version. The issue is that sometimes we have `string` and `stringCaptialized`, and sometimes we have `string` and `stringLowercase`. I think we should just have one.

In gravity-force-lab it worked really well to have everything be lowercase and then to specify `Capitalized` as a suffix when needed. 

Also note that I prefer "capitalized" to "uppercase" since it is more often just the first letter that is uppercase.

Here are a few examples of items that need attention:
* SOLUTE_AMOUNT_STRINGS_LOWERCASE
* redCapitalizedString
*SOLIDS_STRINGS_LOWERCASE
* cobaltIINitrateLowercaseString (in these cases I think "lowercase" is appropriate since the capitalized version is in the normal strings, and we aren't going to change those)
* etc

What do you think @twant, how would you like this to look?

**Comment by twant** [comment]
I think it makes sense to just use string and stringLowercase. I might even advocate for stringCapitalized and stringLowercase, as it will help keep track of the items that do require both sets. I am also realizing that we need consistency with parameter names as well. Adding an item to this to make sure that I check that they're all called `isCapitalized`. I feel fine about variation in their default values as long as the parameter names are the same. Sound good to you, @zepumph?

**Comment by zepumph** [comment]
I think the variation is default values could be ok, especially if they have reasonable defaults for that case (like most of that particular function's usages want lowercase), but I think you should go into the audit with a preferred default for it (like isCapitalized=false), and then have to prove to your self that it should be different. 

I don't think it is reasonable to just keep the same default because it is what is currently there.


>I might even advocate for stringCapitalized and stringLowercase, as it will help keep track of the items that do require both sets.

That is a good idea! Especially when they are obvious pairs of items that feel like there isn't a default, but instead like they are on equal footing.

Also please note that for https://github.com/phetsims/molarity/issues/174 I created `StringCasingPair` that may be useful here. Please keep that in mind while you are refactoring.

**Comment by twant** [comment]
Okay, I think I've cleaned this up a bit. Assigning over to you to take a look, @zepumph!

**Comment by zepumph** [comment]
Updated doc above. closing
