### ISSUE TITLE
VolumeDescriber review

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#182]
- [x] `concentrationDescriber` is not used, and should not be passed as a param to this type.
- [ ] `currentRegion` is a number, and should likely be called `lastVolumeRegionIndex`. This also likely applies to https://github.com/phetsims/molarity/issues/180.

>tracks whether volume has just increased or decreased
- [x] TURN IT UPPPPP
- [x] `volumeToIndex` could use an assertion in the `else` statement as a sanity check.

**Comment by zepumph** [comment]
The last item really applies to #180 and should be done at the same time I think. Everything else here has been done. @twant over to you.

**Comment by twant** [comment]
@zepumph looks great, thanks so much! Closing (and will address the other item with #180)
