### ISSUE TITLE
Normalize values in `*ToIndex` functions

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#183]
For any index mapping function that isn't handled by https://github.com/phetsims/molarity/issues/173 because there are custom region ranges, these values should be normalized. This is the decision that came out of https://github.com/phetsims/a11y-research/issues/146, and was then implemented in gravity-force-lab(-basics). 

Functions to update:
* volumeToIndex
* soluteAmountToIndex

Algorithm:
* Replace each of the hard coded numbers with their counterparts normalized based on the range of the input.
* In the function add a line to the beginning to normalize the input (either volume or soluteAmount) and then compare it against the newly normalized values.

**Comment by zepumph** [comment]
soluteAmountToIndex is already handled because the range was from 0 to 1 moles already

**Comment by zepumph** [comment]
@twant this is complete, please review and feel free if you have no thoughts.

**Comment by twant** [comment]
Thanks, @zepumph! Just merged this into my local changes and it looks good! will push the whole thing shortly (and updated the relevant issues). Closing this one -- thanks so much for your help!

**Comment by zepumph** [comment]
I really messed this one up. The algorithm for normalizing is `(x-min)/(max-min`. We were just diving by the max. Instead we can use Range.getLength.

Furthermore, in soluteAmountDescriber, we don't need to recalculate the values, because the current range is already between 0 and 1, but we still need to normalize it to be prudent.

**Comment by zepumph** [comment]
@twant anything else here?

**Comment by twant** [comment]
No, this looks good to me, and I checked to make sure the regions seem to be mapped appropriately. Closing!
