### ISSUE TITLE
"state" terminology in descriptions

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#185]
From #184, I feel like there are a fair number of places where the word "state" is being used, but in general it is pretty vague, and feels like a catch-all for "description" or something like that. Could we discuss potentially using terminology that is more specific to the use case?

Examples:

* `getQualitativeConcentrationState` returns a string. I'm not sure what "state" is trying to refer to right now. It is filled in to the `stateInfo` var in MolarityAlertManager. What is the different between a description in general and a "state" description? Are all state-related descriptions marked as such?
* `ConventrationDescriber.lastSaturationState` has similar issues in my opinion. On its own it makes sense that it is keeping track of the last value of model saturation, but again `state` seems vague, and like there could be a more specific word. Perhaps `lastSaturationValue` or `previouslySaturated` (the latter would likely require some logic change).

What do you think @twant?

**Comment by twant** [comment]
Went through and changed some usages, or added more documentation explaining what is meant by "state". @zepumph would you like to review?

**Comment by zepumph** [comment]
That is looking really nice. Thanks!
