### ISSUE TITLE
solute amount aria values text depends on current solute

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#187]
Discovered while working on https://github.com/phetsims/molarity/issues/165#issuecomment-563452630.

Here is a screenshot demonstrating it. I just loaded the sim and then changed the solute once:
![image](https://user-images.githubusercontent.com/6856943/70475677-86080f80-1a81-11ea-8974-fadc4a8ada9f.png)

We can pass `a11yDependencies` into the sliderOptions to remedy this

**Comment by zepumph** [comment]
Please review @twant, close if all is well.

**Comment by zepumph** [comment]
@twant and I found a bug here, we want to support client dependencies without blowing away the default in VerticalSlider. @twant still assigned for a spot check.

**Comment by twant** [comment]
Looks good! Closing. Thanks @zepumph
