### ISSUE TITLE
Split up ConcentrationDescriber?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#188]
I'm almost positive that we don't want to do this. But I want to ask @twant first

From the CRC:

>Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?

Do you think it could work to have a `SaturationDescriber` and a `ConcentrationDescriber`? 

I don't think that 500 lines of code is too large for a file at all, I just wanted to see if that could be a nice refactor. If you don't think so @twant, please close.

**Comment by zepumph** [comment]
#165

**Comment by twant** [comment]
@zepumph I took a look, and I think it makes sense to split these two up. The only thing I don't love is that ConcentrationDescriber still needs to keep a link to PrecipitateAmountProperty in order to determine saturationStateChanged, but I think the rest is much cleaner! 

Assigning over to you for review!

**Comment by zepumph** [comment]
I sorta wish that `saturationValueChanged` could be handled by the model, but I can't figure out how that could be done well. 

At first I was pondering using an Emitter from the model that says "the saturation was toggled," but I didn't know how to then "clear" that value on next change. That would be a secondary event that wouldn't really know how to communicate with the event of "event that is causing alert to fire". Sorry if that doesn't make sense, but it is likely not going to work.


Anywho. Everything else looks great and I'm ready to close if you are.

**Comment by twant** [comment]
Sounds good! Thanks for reviewing. And I agree -- seems like something that could be handled more efficiently, but I'm having trouble thinking of how. Closing!
