### ISSUE TITLE
Convert memeber vars to private vars when applicable

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#197]
I'm looking through describers and seeing a fair number of variables that are only needed in the constructor, but are still stored on `this`. For example `currentRegion` used in a few describers. Can we make those `let` vars instead?

**Comment by twant** [comment]
updated! @jessegreenberg would you mind reviewing and closing when you have a minute?

**Comment by twant** [comment]
@jessegreenberg and I looked over this today & closed
