### ISSUE TITLE
Publish an RC version

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#198]
I think we are close to an RC, but seeing as this is my last day for vacation, I think we should likely make a central issue for all to see the current progress in the repo. 

Still to do:
- [x] All issues marked with the "code-review" label except https://github.com/phetsims/molarity/issues/189
- [x] @twant and @terracoda, it would be good for you two to give it another once over, seeing as lots of work has been done in the sim recently. Though most of it is superficial, it would be good to make sure no design regressions go unnoticed. 
- [ ] QA credits: https://github.com/phetsims/molarity/issues/140 (assign to KW after the first RC test).
- [x] @jessegreenberg and @twant to create the RC together (hopefully sometime next week).

**Comment by twant** [comment]
@terracoda, @jessegreenberg and I went ahead and created the RC, but would still love your eyes on it (I didn't see anything out of place, but wanted to make sure you didn't see anything amiss!). The link is: https://phet-dev.colorado.edu/html/molarity/1.5.0-rc.1/phet/molarity_a11y_view.html. Thanks!

**Comment by terracoda** [comment]
Tagging RC issue for this sim https://github.com/phetsims/QA/issues/464, too.

@twant, @jessegreenberg, @Matthew-phet, I just had a careful listen to Molarity on master and on the 1.5.0-rc link
[1.5.0-rc link](https://phet-dev.colorado.edu/html/molarity/1.5.0-rc.1/phet/molarity_a11y_view.html)

I think things are sounding fantastic. I didn't use the A11y View much. I was focusing on the actual responses.

I found one issue - one edge case which may have not have been documented in the design doc, even (sorry). The case is when the user uses home and end keys on the Solute Amount slider and jumps to zero solute from a state where the solution was previously saturated. The solution is described "lighter" which is kind of true, but it might be more appropriate to say it is clear and that it is water. 

**The responses in question** - when jumping from a saturated solution directly to pure water:
- "No longer saturated. Solution lighter, zero concentration." (when Solution Values not checked)
- "No longer saturated at 0.000 molar. Solution lighter." (when Solution Values is checked)

**For comparison the response** - when jumping from a concentrated solution - NOT yet saturated - to water:**
- "Zero concentration. Solution pure water."
- "Zero concentration. Solution pure water."

**Possible Solutions:**
**Option 1:** - Combine "No longer saturated." with our current pure-water phrase to explicitly make it clear that the solution is both no longer saturated and now pure water.
- No longer saturated. Zero concentration. Solution pure water.
- No longer saturated. Zero concentration. Solution pure water.

OR

**Option 2:** Use our pure-water phrase and assume learners will know/deduce this state is no longer saturated.
- Zero concentration. Solution pure water.
- Zero concentration. Solution pure water.

@Matthew-phet, I need your thoughts here.

**Comment by terracoda** [comment]
@Matthew-phet , do you think we should leave as-is, or got with option 1 or 2 if you think we sould change the response.

**Comment by terracoda** [comment]
Just adding 2 screen shots from the A11y View showing the responses in question:
![Screen Shot 2019-12-19 at 11 08 04 AM](https://user-images.githubusercontent.com/1902116/71185922-e30c7e00-2256-11ea-9b88-82520cd214e0.png)

![Screen Shot 2019-12-19 at 11 08 59 AM](https://user-images.githubusercontent.com/1902116/71185932-e7389b80-2256-11ea-8971-8161a3f0f82a.png)

**Comment by jessegreenberg** [comment]
Thanks @terracoda, moving comments to a new issue to track outside of this one.

**Comment by terracoda** [comment]
Thanks @jessegreenberg for making a new issue, and I checked the review item in https://github.com/phetsims/molarity/issues/198#issue-537840314. I've done my review.

**Comment by zepumph** [comment]
There is already an issue open for the last remaining checkbox, and an RC version has been created. I'm going to close this.
