### ISSUE TITLE
Value labels move up in down a small amount

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#200]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem Description
For https://github.com/phetsims/QA/issues/464.
The labels for Solute Amount and Solution Volume used to line up with and follow the slider bars. This is the behavior in the published version. In this R.C. the labels move up and down a much smaller amount and don't line up with the slider bars.

**Visuals**
![tinymovement](https://user-images.githubusercontent.com/41024075/71207712-ba8b8080-2264-11ea-9714-600472d10fe8.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molarity‬
URL: https://phet-dev.colorado.edu/html/molarity/1.5.0-rc.1/phet/molarity_all_phet.html
Version: 1.5.0-rc.1 2019-12-19 01:13:41 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by twant** [comment]
In investigating this, it looks like this issue was not present in version 1.5.0-dev.28 (the most recent dev version). In looking at commits that have occurred since, the one that looks most likely to have affected this is the work done to switch the dimensions of VerticalSlider https://github.com/phetsims/molarity/commit/92dfa1b83705c2683028f0b7014aab30d86c8ff7. I'll investigate this week. @zepumph, when you are back (if this has not been resolved by then), would love your thoughts on whether this could have affected these labels, or whether you think we should investigate elsewhere!

**Comment by twant** [comment]
Fixed this by making the value label node positions depend upon the slider's height and not its width (since those values were switched to make more sense with the vertical orientation of the slider). @zepumph would love your review of this one to make sure it looks good to you!

**Comment by jessegreenberg** [comment]
I reviewed the change, it looks good to me and very reasonable given the changes ini https://github.com/phetsims/sun/issues/544 (related to https://github.com/phetsims/molarity/commit/92dfa1b83705c2683028f0b7014aab30d86c8ff7)

**Comment by twant** [comment]
Awesome, thanks for reviewing, @jessegreenberg! @KatieWoe I think it's ready for your review to ensure it's ready to close!

**Comment by twant** [comment]
Nevermind, @jessegreenberg explained the process of just marking these issues for review for the next RC (thanks very much, Jesse!). I'll just label this a ready for qa.

**Comment by KatieWoe** [comment]
Looks good in rc.3
