### ISSUE TITLE
Molarity arrow covers long strings

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#201]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/464
When strings are long and the arrow that indicates solution concentration is at the bottom of its bar it can cover up the string. The string has to be fairly long for this to happen, so it is likely not a big issue.

**Visuals**
![overlappinglong](https://user-images.githubusercontent.com/41024075/71218094-81abd580-227d-11ea-9da4-d9660bd680fe.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/molarity/1.5.0-rc.1/phet/molarity_all_phet.html?stringTest=long
Version: 1.5.0-rc.1 2019-12-19 01:13:41 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Note: Solution Values needs to be off for this.

**Comment by KatieWoe** [comment]
Note: It also happens at the top of the bar

**Comment by twant** [comment]
In testing different string lengths, this begins to be a problem with strings longer than 8 characters (so it really doesn't take a very long string to make this happen. This does seem like something worth addressing if possible -- @emily-phet who would be the best person to consult about adjustments to the visual layout of the sim (I imagine that these labels would need to be shifted a bit so they are further above and below the concentration scale)?

**Comment by jessegreenberg** [comment]
Here is what it looks like with stringTest=double, which is still readable in my opinion
![image](https://user-images.githubusercontent.com/6396244/71524052-bcbf9180-2899-11ea-9b34-65c87f0f82bf.png)

@ariel-phet can you please review and comment on whether a change is required for this and if so who the responsible designer should be?

**Comment by zepumph** [comment]
I'll add myself here too so I don't let this drop. @ariel-phet what are your thoughts.

**Comment by ariel-phet** [comment]
@zepumph I think this issue could be addressed by moving the indicator arrow to the right, and using a hairline/dashed line to connect it to the bar (blackbody spectrum uses this approach and even though in that sim the indicator is interactive, I think it could work well), I think a hairline would be best. Some more breathing room would be appropriate in my opinion.

**Comment by emily-phet** [comment]
@ariel-phet I like the idea of the hairline connecting the arrow end to a specific value on a vertical scale, and it would be nice to have some uniformity where possible across sims. I do wonder, though, if the fact that in Molarity the arrow points to a gradient (rather than a solid line) and takes on the color of the gradient at that point - makes this a different case. 

Perhaps leaving it as is may be preferable in this case, since the only text that appears at the bottom of the vertical scale is either the numeric "0" or the word "zero", and even if there is overlap for some languages, there are many cues (the fact that it's the very bottom of the scale, auditory cues, etc.) to help indicate what that lowest arrow position is. 

Thoughts?

**Comment by zepumph** [comment]
>Perhaps leaving it as is may be preferable in this case, since the only text that appears at the bottom of the vertical scale is either the numeric "0" or the word "zero", and even if there is overlap for some languages, there are many cues (the fact that it's the very bottom of the scale, auditory cues, etc.) to help indicate what that lowest arrow position is.

I would say this is the philosophy we used in ohms-law and resistance-in-a-wire formulas, in which they are translatable letters, but also we don't adjust the formatting, such that if you use long letters it is easy to mess things up. 

![image](https://user-images.githubusercontent.com/6856943/71753203-58b74300-2e2e-11ea-9d32-a24e8f4c2d7f.png)

That said, I don't have any preference about leaving it the same or applying a dashed line. For the dashed line suggestion would we want to make that the same color as the arrow (on the gradient)? That may be nicer than just having it be black (I don't know, I'm no designer).

**Comment by ariel-phet** [comment]
@zepumph I think the RIAW example is not really apples to apples, it is very unlikely for people to translate those characters to multiple characters as that would be mathematically inconsistent, each of these characters representing a single variable. 

@KatieWoe please go through current translations of Molarity and see if this issue exists, if so I think we should change to the hairline (and yes @zepumph if easy match that line to the color of the arrow). 

If there is no issue in present translations, let's leave as is.

**Comment by emily-phet** [comment]
@ariel-phet Just checking to see if you noticed my [comment](https://github.com/phetsims/molarity/issues/201#issuecomment-570450296) above.

If the hairline gets put in, it's possible that at low concentrations it may be difficult to see for some of the solutions due to low contrast. We also really need this sim published urgently, so ideally the hairline is not needed.

**Comment by KatieWoe** [comment]
I only saw three languages where there was any touching/overlap, and it was fairly minor. I don't think the fix is need, but I'm posting images of the three languages in case you disagree.
Danish:
![da](https://user-images.githubusercontent.com/41024075/71830904-0318ab80-3065-11ea-8fde-bac673f231f3.png)
Greek:
![el](https://user-images.githubusercontent.com/41024075/71830951-19266c00-3065-11ea-8f8d-f2b7077ff374.png)
Tamil:
![ta](https://user-images.githubusercontent.com/41024075/71830975-26dbf180-3065-11ea-88a1-0385dd3ff6e1.png)

**Comment by ariel-phet** [comment]
@KatieWoe appreciated. Closing
