### ISSUE TITLE
Query Parameter "?stringTest=xss" cuts off almost all of the sim

### ISSUE THREAD

**Issue by jaspearias** [phetsims/molarity#203]
<b>Test Device</b>

MacOS 10.13

<b>Operating System</b>

MacOS 10.13

<b>Browser</b>

Google Chrome

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/464 

When entering query parameter "?stringTest=xss" the sim gets cut off almost completely. The only thing that can be tested is the undo button, sound button, keyboard nav button, and PhET info button.

<b>Visuals</b>

https://drive.google.com/file/d/1g07bXKsUQH9lSjDgpV-Z4pUm9OVAuqZt/view?usp=sharing

**Comment by twant** [comment]
From the QA book, I found this info about stringTest=xss:

?stringTest=xss: cross site scripting
This query parameter puts JavaScript into every string. The page should not redirect.
If the simulation does not redirect to another website, the simulation passes this test.
If the simulation crashes or fails to load, the simulation still passes this test.

It seems from this that although the sim doesn't render correctly, it should still pass this test as long as it doesn't redirect to another site. @KatieWoe can you chime in here for guidance on how to proceed with this issue?

**Comment by zepumph** [comment]
>It seems from this that although the sim doesn't render correctly, it should still pass this test as long as it doesn't redirect to another site.

Agreed. The sim does not need to support anything with `?stringTest=xss` except making sure that it doesn't redirect. I think we should close this, but let's assign @jaspearias to do so after reading this to make sure we are all on the same page.
