### ISSUE TITLE
Sound: In Solute Combobox do the solutes have a tone?

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#204]
In the [RC version for Molarity](https://phet-dev.colorado.edu/html/molarity/1.5.0-rc.1/phet/molarity_all_phet.html), I recently noticed that in the combobox interaction there are no longer associated tones for each of the different solutes as you cycle through the list.

Each solute did have an associated tone at one time. Perhaps it was decided to remove these tones?

@jbphet could you verify that there is no longer an associated tone for each of the solutes in the combobox interaction? Apologies if I missed that sound design change.

Tagging RC Test [QA/issues/464#](https://github.com/phetsims/QA/issues/464#issue-540018825)

**Comment by jbphet** [comment]
I just tested this RC on Chrome+Win10, Firefox+Win10, and Safari+MacOS 10.13.6.  In all cases, I was able to hear the selection sound for the solute.  I tested both mouse and keyboard navigation.

@terracoda - I'm not sure what you're seeing, so I would suggest re-testing and making sure that what you experienced wasn't some sort of anomaly.  If you are able to reproduce this, please record the browser, browser version, OS, and OS version.

Please note that the sounds are not exactly "tones".  The are more like fast sequences of notes that vary based on the selected solute.  The sound only fires once the selection is made.

**Comment by terracoda** [comment]
I'll listen again @jbphet, I might have been expecting the sound at the wrong time.

**Comment by terracoda** [comment]
All is good, apologies. I thought I was supposed to hear a sound as I cycled through the solute options. The solute sounds are playing fine upon selection.

Thanks @jbphet! I am closing this issue.
