### ISSUE TITLE
Move slider alerts from model listeners to slider callback

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#206]
From https://github.com/phetsims/molarity/issues/189, it may be possible to fix an order dependency by running these slider alerts from the slider callbacks instead of by linking directly to the model Properties. I'll see how it sounds before implementing.

**Comment by zepumph** [comment]
I do not think that anything has changed here. I did a pretty thorough regression test and feel good about things. Before closing I want to run this change by @terracoda. No instead of volume/solute amount alerts being triggered from the Property, they are being triggered only from the end drag of the Slider. In normal use this ends up being basically the same (except better for the code due to issues from https://github.com/phetsims/molarity/issues/189). The only reason this would be bad is if we are sometimes doing this alert from changes outside of the two sliders, which I do not think is occurring. @terracoda please close if you feel like this is alright.

**Comment by terracoda** [comment]
@zepumph, to test/verify this am I just supposed to listen to the sliders to see if things are happening in the correct order?

**Comment by zepumph** [comment]
Yeah sounds great. Also just simply making sure that the slider alerts sound as they should (all or nothing, not as much the individual logic)

**Comment by terracoda** [comment]
And mobile, too? If so, please post dev link for emailing to my phone.

**Comment by zepumph** [comment]
https://phet-dev.colorado.edu/html/molarity/1.6.0-dev.1/phet/molarity_en_phet.html

**Comment by zepumph** [comment]
Please close if all sounds as expected.

**Comment by terracoda** [comment]
When testing yesterday, I didn't notice anything strange.
