### ISSUE TITLE
New Screenshot

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#209]
Probably good to do with this new publication. I'll assign when we are ready. Note https://github.com/phetsims/QA/issues/464#issuecomment-570664520

**Comment by jessegreenberg** [comment]
OK it is probably time for this. @KatieWoe what is usually the next step for an issue like this?

**Comment by KatieWoe** [comment]
When it comes up for rc with the rc you want images taken with, assign this issue with the "issues to verify"

**Comment by jessegreenberg** [comment]
Ah, the rc has been prepared and no more graphical changes will be made, we are ready for this.

**Comment by KatieWoe** [comment]
@arouinfar any changes you want to the existing ones?

**Comment by arouinfar** [comment]
@KatieWoe please retake the current screenshots. I don't have any changes to suggest.

**Comment by KatieWoe** [comment]
Above commits should do it.

**Comment by jessegreenberg** [comment]
Great, thanks! And I see that you put them in the rc branch too. Closing.
