### ISSUE TITLE
Possible to use touch to move slider and select solute at once

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#214]
For https://github.com/phetsims/QA/issues/464. Fairly minor multitouch issue.
I noticed an odd behavior in molarity. It's in the published version. You can use one touch to both change a slider and select a new solute.
1. Use touch to open the solute menu
2. Drag finger along options
3. Without lifting up, move finger over a slider to grab it
4. Move finger back to menu and lift up to make a selection

![verymildoddness](https://user-images.githubusercontent.com/41024075/71929920-e90bc580-3157-11ea-9714-790cb5ad2f17.gif)

**Comment by jessegreenberg** [comment]
Confirmed. I suspect this is not an issue with Molarity but with ComboBox and touch snag.

**Comment by jessegreenberg** [comment]
Yes, this is happening in beers-law-lab as well.

**Comment by jessegreenberg** [comment]
I made https://github.com/phetsims/sun/issues/556 to see if this needs to be fixed, on hold until that issue is resolved or closed.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/sun/issues/556 has been closed and determined to be low priority so we are going to proceed with publishing without addressing this issue.
