### ISSUE TITLE
Unused capitalized solute amount strings

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molarity#218]
In #217 I noticed that soluteAmountRegions.capitalized strings don't seem to be used in this sim right now. Both usages (screen summary and aria-valuetext) use lower case

![](https://user-images.githubusercontent.com/6396244/72027850-80534480-324e-11ea-963b-f8163f57a9a4.png)

![](https://user-images.githubusercontent.com/6396244/72027863-8812e900-324e-11ea-8802-9382d831cd8e.png)

@zepumph is this correct and if so can the capitalized form of strings be removed?

**Comment by zepumph** [comment]
I trust you if they aren't being used currently. I think that in general aria-valuetext is supposed to be lowercase, and alerts are supposed to be capitalized. @terracoda does it seem right to you the way regions are capitalized now? If so please close, otherwise assign back to @jessegreenberg.

**Comment by terracoda** [comment]
There were a lot issues around capitalization for this sim. The general strategy, is indeed, to follow what @zepumph said above.

If a region variable never appears at the beginning of a sentence in an alert (context response) or in the pdom (dynamic state description) then there would be no use of the capitalized strings for region names.

This seems very right to me, @jessegreenberg. Assign to me if you would like me to review in detail.

**Comment by terracoda** [comment]
@jessegreenberg, I verified in the A11y View. It all looks to good to me - no capitals needed on region names for Solute Amount or Solution Volume.

**Comment by jessegreenberg** [comment]
OK, thanks! Ill remove the capitalized strings and simplify the function since they are not used.

**Comment by jessegreenberg** [comment]
Inspecting the code it looks like the capitalized form used to be used when `useQuantitativeDescriptionsProperty` was true. But now none of these strings are used when quantitative descriptions are being shown. So it feels safe to remove.

**Comment by jessegreenberg** [comment]
This was moved into the next RC, closing since there is nothing specific for the qA team to verify.
