### ISSUE TITLE
Long stringtest causes sliders to change position

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/molarity#219]
**Test device**
Windows 10 Laptop
**Operating System**
Windows 10
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/QA/issues/476

The long stringtest leads to the sliders changing position.
**Steps to reproduce**
1. Add query parameter ?stringTest=long
2. Observe sliders
**Visuals**
![2020-02-06MlrtyLngSttst](https://user-images.githubusercontent.com/54685448/73984178-52b4f600-48f5-11ea-929e-a5a53761e63d.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/molarity/1.5.0-rc.3/phet/molarity_all_phet.html?stringTest=long
Version: 1.5.0-rc.3 2020-02-06 16:47:45 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
Language: en-US
Window: 1600x786
Pixel Ratio: 1.2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks for reporting @loganbraywork, but I don't think this issue requires time. The layout for i18n needs to be graceful but it doesn't need to be identical. The example gif here shows graceful handling of extremely long strings.

Closing.
