### ISSUE TITLE
Update Teacher Guide, Molarity will be published soon

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#220]
From #99, we need to update the Teaching Guide for Molarity. It will soon be published with the following features:
- alternative input
- interactive description
- interactive description on ios
- sound & sonification

Tagging @BLFiedler and assigning to @arouinfar. Please re-assign as needed.

There is a special note about the description which may be relevant to the Teacher Guide. This is that the exact saturation point is described as, "At max concentration. Solution darkest."

**Comment by BLFiedler** [comment]
I can add the A11y features and sonification section similar to John Travoltage and the others I've recently done. Is the Molarity Sound Design Doc updated?

**Comment by terracoda** [comment]
@BLFiedler, I don't know about the state of the Sound Design Doc, maybe @Ashton-Morris could comment? If all you need is the list of important sim sounds, I can give you that.

**Comment by BLFiedler** [comment]
@arouinfar Let me know if there are other modifications you need to make and I'll wait until you've made your edits

**Comment by terracoda** [comment]
The sim has general UI sounds (Reset All button, Checkbox checked and unchecked sounds). There is also a sound when the List of Solutes pops up. I am not sure if that is a general UI sound for an opening combobox or if it is specific to Molarity. The scaled sounds for the Solutes, I think are specific to Molarity. If this detail is important, reach out to @Ashton. This is our first combobox interaction. 

For the important sounds more related to learning goals we have:
- When not saturated, there is a changing tone for concentration level; lower pitched tone = more concentrated and higher pitched tone = less concentrated. This means more solute or less volume when not saturated = lower pitched tone and vice versa.
- When saturated, the sounds changes to a changing tinkle sound that represents the presence of precipitate; lower-pitched tinkle = more precipitate ("more solids") and a higher-pitched tinkle = less precipitate ("less solids"). This means less solute or more volume when saturated results in less solids (higher pitched tinkle).

As mentioned above there are sounds for the Combobox - opening and closing sounds, and when the Solute is changed a different sound plays for each Solute. There is a little triple bell sound that plays when the Solute is changed and this bell sound is scaled. The solute at the top of the list has the lowest pitch, the one at the bottom of the list has the highest pitch.

I think that's it for sounds.

**Comment by arouinfar** [comment]
@BLFiedler I've already updated the Teacher Tips in #161. The latest version can be found in the sim folder on Drive: https://drive.google.com/drive/u/0/folders/0B6CMwxdP0NGYdDltZHlxdS12Zzg

**Comment by BLFiedler** [comment]
Awesome. I can take care of this Monday when I have access to a Mac with Pages.

**Comment by BLFiedler** [comment]
Will update to include sound features & a11y icons, but will not add reference to Sound Features video until it is complete (issue #221 )

**Comment by terracoda** [comment]
Molarity almost everything: 
- Interactive Description, Alternative Input, Mobile A11y, and Sound.

Just missing Zoom/Magnification.

**Comment by Ashton-Morris** [comment]
I have updated the Molarity Sound Design document [which can be found here.](https://docs.google.com/document/d/1J05jC0mWOBz7S3FWTjVMvs7CiYpXibi5trA6xABPYw8/edit#)

If there are any specific details about the sound, names, and descriptions of sounds needed,  hopefully this document helps with that.
