### ISSUE TITLE
Molarity Sound Features Video Script and Recording

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/molarity#221]
Make sound features video script and review with team

https://drive.google.com/open?id=1wWDkTqpher8ghC-9okw2cQ0RHTOIMFOwgQ-FNlqB7CQ

Recording will happen after.

**Comment by BLFiedler** [comment]
Update Molarity Teacher Tips to include presence of Sound Features video when complete

**Comment by emily-phet** [comment]
@BLFiedler Just pinging you on this - we had the postmortem and are hoping to get all loose ends with this sim wrapped up soon. Please mention here in March if it seems like you will or will not be able to finalize the Sound Features and Teacher Tips this quarter.

**Comment by BLFiedler** [comment]
Yeah - plan was to devote time to that this week. I added a question to the design doc that would be helpful in creating the script for Molarity. @Ashton-Morris , can you take a look and answer if you can?

**Comment by emily-phet** [comment]
@BLFiedler - I edited the doc in response to your question.
The presence of the "tinkle" sound indicates saturation. Change in pitch of the "tinkle" sound indicates amount of precipitate.

**Comment by BLFiedler** [comment]
First pass on a Molarity script made:

https://docs.google.com/document/d/1wWDkTqpher8ghC-9okw2cQ0RHTOIMFOwgQ-FNlqB7CQ/edit?usp=sharing

// Start recording
Welcome to PhET Interactive Simulations!
In this video, I’ll show you the sound features in the simulation Molarity.
In Molarity, you can explore the relationships between solute amount, solution volume, and solution concentration.
To begin, choose a solute //pick NiCl2// and select a slider to investigate its effect on the concentration of the solution.
You can control the amount of solute...
//Move the Solute Amount slider up and down slowly
Or the volume of the solution...
//Move the Solution Volume slider up and down
Did you hear a tone change as the sliders moved? The pitch of this tone increases and decreases with the concentration of the solution! 
A higher concentration, a lower tone...
//Drag solute all the way up, and volume all the way down.
A lower concentration, a higher tone!
//Drag volume all the way up and solute all the way down.
Change the solute and see if you can hit Saturation!
//Change to KMnO4 with previous slider values (solute low, volume max), slowly slide solute up
As you get past saturation, that tone becomes a twinkle that decreases in pitch with more precipitate!
Explore each solute to find its saturation point!
Thanks for watching! If you want general tips on using the sim with your students, then check out the Video Primer!
// End recording.

**Comment by emily-phet** [comment]
Thoughts:
- The sim's design is to scaffold exploration of "Drink Mix" first, so would be good if you started with description of the solute and solution sliders first, before combobox. 

Otherwise - very nice!

**Comment by BLFiedler** [comment]
Ah, you know what, I changed the solute to Nickel because I saw it did not reach saturation. Turns out I did not explore the drink mix first, which also does not reach saturation. Easy change, no effect on message :)

**Comment by BLFiedler** [comment]
Draft 1 complete (no intro/outro, might need some sound quality finesse): https://drive.google.com/file/d/1DwjCuFAAIDa8aVZ2OqnjuqqRTIoxGGyI/view?usp=sharing

**Comment by emily-phet** [comment]
@BLFiedler - Beautiful. Clear, succinct, and a lovely sound design. Great work! Please move it along to publication on the website.

**Comment by BLFiedler** [comment]
Re-recorded for audio and change to pitch language ( "deeper" similar to GFL). Next steps (by end of day tomorrow): Adding intro & outro, uploading to YouTube, Captions, and addition to For Teachers section of simulation webpage.

**Comment by BLFiedler** [comment]
Published

https://www.youtube.com/embed/4s1Wy8ofXwQ
