### ISSUE TITLE
Update Sim page credits

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#228]
This is in response to the Molarity post-mortem meeting. 

@terracoda you mentioned you may have some insight into doing this. If it's as simple as just copying some text from the sim into the admin interface, can you please do this - perhaps during status meeting this week?

In the future, we will work more with a fully integrated team and this will be on the general sim designers checklist. Also, we can show @Matthew-Moore240 how to do this, so he is able to do it for MAL, etc.

**Comment by terracoda** [comment]
@emily-phet, is this about updating the Sim Credits page on the website?
Maybe we can re-visit this issue at our next team meeting.

**Comment by terracoda** [comment]
I'll see if I can get Amy or Amanda to show me what I have to do.

**Comment by arouinfar** [comment]
@terracoda you can edit the credits on the sim admin page (same place you go to tag a11y features).
![image](https://user-images.githubusercontent.com/8419308/95483778-e3dce080-094c-11eb-958d-01565b0e1e8c.png)

**Comment by terracoda** [comment]
Thanks @arouinfar, I see where to put the people now, that's great. Over in https://github.com/phetsims/website/issues/995, I am asking how to make the list of people.

I'll close this issue as it is just for Molarity, which is technically updated, and keep https://github.com/phetsims/website/issues/995 open until I figure out how to make the list.
