### ISSUE TITLE
add QA credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#23]
This sim currently has no QA credits. @ariel-phet please let me know who should be credited.

**Comment by ariel-phet** [comment]
I think to be safe lets credit the whole QA team (since the test matrix is not quite done yet and a few other testers might hop on)

Elise Morgan, Bryan Yoelin, Steele Dalton, Oliver Orejola

**Comment by pixelzoom** [comment]
Done, with QA credits in proper alphabetical order: 

`qualityAssurance: 'Steele Dalton, Elise Morgan, Oliver Orejola, Bryan Yoelin'`

Closing.
