### ISSUE TITLE
Mirror wrapper does not work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#236]
For https://github.com/phetsims/QA/issues/642. Win 10 Chrome. Seen in https://phet-dev.colorado.edu/html/molarity/1.4.13-rc.1/phet-io/wrappers/mirror-inputs/mirror-inputs.html.
When you first click to do something in the top sim, the bottom sim freezes and does not respond. The top seems to keep working.
![mirrordoesntmolarity](https://user-images.githubusercontent.com/41024075/117363435-d1db0600-ae79-11eb-836c-2588705f7cb3.gif)

**Comment by KatieWoe** [comment]
This is happening with resistance in a wire as well. https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.13-phetiorc.1/resistance-in-a-wire_en-phetio.html?phetioStandalone

**Comment by jonathanolson** [comment]
Matched in molarity, going to look into auto-applying the patch elsewhere where it's relevant.

**Comment by KatieWoe** [comment]
Wait, I put the resistance in a wire comment in the wrong issue.

**Comment by KatieWoe** [comment]
Should have been https://github.com/phetsims/capacitor-lab-basics/issues/291

**Comment by jonathanolson** [comment]
This looks to be patched up

**Comment by jonathanolson** [comment]
Closing, handled in maintenance release deployment.
