### ISSUE TITLE
Corresponding item not found for concentration

### ISSUE THREAD

**Issue by samreid** [phetsims/molarity#237]
CT is showing this error:

```
molarity : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625013793046/molarity/build/phet/molarity_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22molarity%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1625013793046%22%2C%22timestamp%22%3A1625015649083%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: Corresponding item not found for concentration: 2.25
Error: Corresponding item not found for concentration: 2.25
```

This was caused by my commit earlier today: https://github.com/phetsims/molarity/commit/f4ea537b0ff1a78fad10efc095c54db5dacef6c3

**Comment by samreid** [comment]
I reverted the change, but it looks very suspicious because call sites are not guarding against return values of undefined.  Assigning to the responsible dev and marking as blocks-sim-publication.

**Comment by zepumph** [comment]
Thanks! There was a bug about how the method was called in a place. I converted the hard error to an assertion, added an earlier assertion, and fixed the lint rule you disabled. Fuzzing is now passing. Closing
