### ISSUE TITLE
1.2.0 Publication items

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/molarity#25]
Remaining Checklist items S2015R milestone

**Developer**

  - [x] Double check relevant entries in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md

**Design/Admin**
- [x] Rosetta test (Opening sim to trusted translators for beta)
- [x] Check teacher tips are up to date
- [ ] Check sim primer is up to date
- [x] Review process with QA team.

**Comment by ariel-phet** [comment]
@amyh-phet are the teacher tips for this sim up to date? Is a sim primer in the works?

**Comment by amyh-phet** [comment]
@ariel-phet   I have a draft of the teacher tips.  I will meet with Trish today and have her proofread.  Draft of script for primer is in the works - hope to have Trish look at it today as well.

**Comment by ariel-phet** [comment]
@amyh-phet excellent, please keep as a high priority (I know the primer will take some time due to current production bottlenecks)

**Comment by ariel-phet** [comment]
@samreid -- @pixelzoom said he was not in a position to double check the relevant entries in sherpa. What needs to be done for that checklist item, not 100% clear to me.

**Comment by samreid** [comment]
Since Molarity did not pick up any new dependencies, the sherpa file license file is in pretty good shape.  The main thing that has changed is version numbers, for instance, where it says `‪Molarity‬ 1.2.0-dev.1` it should say `‪Molarity‬ 1.2.0`.  One way to resolve this would be to run the grunt task that regenerates the third-party-licenses.md file.  I'll create an issue assigned to me, at lower priority unless I hear otherwise, so this issue can be reassigned to others to continue with any work required here.

**Comment by samreid** [comment]
Issue created above, reassigning this issue to @ariel-phet to continue/delegate.

**Comment by amyh-phet** [comment]
@ariel-phet   Updated teacher tips are on website.   Primer is in the works (script in review, tentative 1st recording to be done on Oct. 30).

**Comment by pixelzoom** [comment]
@ariel-phet status?

**Comment by ariel-phet** [comment]
Still waiting for primer.

**Comment by amyh-phet** [comment]
@ariel-phet  and @pixelzoom    First recording of primer is done.   Waiting for feedback, then will do a second (and hopefully final recording).   Should be getting feedback by Friday, Nov. 13.  I hope to send the final version to production by Nov. 20.  Be aware that production may take several weeks to complete.

**Comment by ariel-phet** [comment]
The primer projects are being covered by https://github.com/phetsims/tasks/issues/429 and https://github.com/phetsims/tasks/issues/430 closing
