### ISSUE TITLE
Solutions have no color

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molarity#32]
This is true in both master and the recently deployed phetio version in phetsims/tasks/issues/819.

There is no color for any solute, at any concentration. Notice too how the molarity arrow has no color. Here is potassium dichromate as an example:
<img width="1399" alt="screen shot 2017-04-17 at 2 44 52 pm" src="https://cloud.githubusercontent.com/assets/5863899/25104207/ac26a2b6-237c-11e7-8a0e-6c9dd568a010.png">

Here is the current production version:
<img width="1913" alt="screen shot 2017-04-17 at 2 46 27 pm" src="https://cloud.githubusercontent.com/assets/5863899/25104210/af588422-237c-11e7-943d-7bb1989848ca.png">

Seen on macOS 10.12.4 Chrome.
(no troubleshooting information available on phetio builds)

**Comment by pixelzoom** [comment]
Doh! How did I miss that?!?  And looks like it's been a problem for awhile, introduced when the sim was converted from PropertySet to Property.   Fixed in above commit.

**Comment by pixelzoom** [comment]
Ready for test in https://github.com/phetsims/tasks/issues/821.

**Comment by phet-steele** [comment]
Looks good, thanks.
