### ISSUE TITLE
verify credits for 1.3.0 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#33]
QA credits should be revisited. @phet-steele I'll consult with you when RC testing wraps up.

**Comment by pixelzoom** [comment]
@phet-steele Looks like we're getting close to publication.  Please let me know if there are any deltas for the QA credits. Here's what we have currently:

```      qualityAssurance: 'Steele Dalton, Elise Morgan, Oliver Orejola, Bryan Yoelin'```

**Comment by phet-steele** [comment]
@pixelzoom please add Alex Dornan and Ethan Johnson.

**Comment by pixelzoom** [comment]
QA changes pushed to 1.3 and master.  Screenshot of current credits shown below.  @phet-steele please verify, close if this looks OK.

![screenshot_290](https://user-images.githubusercontent.com/3046552/27801595-0bd82c20-5fdc-11e7-8184-ffc070899c89.png)

**Comment by phet-steele** [comment]
👍
