### ISSUE TITLE
"Show values" is not instrumented for PhET-iO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#34]
Related to https://github.com/phetsims/tasks/issues/821...

@phet-steele pointed out that the label on the "Show values" check box is currently not instrumented.

**Comment by pixelzoom** [comment]
Label is now instrumented. @phet-steele please verify in master.

**Comment by pixelzoom** [comment]
In phetmarks instance-proxies:

![screenshot_232](https://cloud.githubusercontent.com/assets/3046552/25459656/8aa42858-2a9c-11e7-81a1-132af177e8b6.png)

**Comment by phet-steele** [comment]
Verified, thanks @pixelzoom.
