### ISSUE TITLE
User suggestion: show values separately 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molarity#35]
I'm a chemistry teacher in Waltham and use many of the simulations to engage my students in chemistry concepts. Recently, I was using the Concentration and Molarity simulations and had a thought about the Molarity simulation. Perhaps its been suggested before but, would it be possible to replace the "show values" button with separate buttons that allow you to show the volume, moles and molarity individually? This would add the functionality of students being able to calculate a missing molarity, moles or volume when 2 are given and allow them to check their work by showing the missing value. Thanks!

**Comment by pixelzoom** [comment]
The downside of this request is that you'd have to toggle 3 check boxes in order to do what you currently do with 1 check box. 

@ariel-phet the original design lead is not longer with the project. Please assign.

**Comment by pixelzoom** [comment]
The customer is presumably asking for something like the mockup below.  This doesn't seem like an improvement to me.

![screenshot_241](https://cloud.githubusercontent.com/assets/3046552/25719691/7d0fcfa4-30c7-11e7-9d31-c285099994e2.jpg)

**Comment by ariel-phet** [comment]
Although I see the reason the user would want this type of functionality, I don't think it makes sense in this particular simulation.

@oliver-phet let the user know we appreciate the suggestion, but in this particular simulation adding that functionality would be problematic from a design perspective.

**Comment by oliver-phet** [comment]
user emailed. closing.
