### ISSUE TITLE
convert to HSlider

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#40]
This sim currently has it's own slider implementation, VerticalSlider.  Change to use sun.HSlider.

**Comment by pixelzoom** [comment]
@zepumph FYI, I'll be taking care of this.

**Comment by zepumph** [comment]
Sounds great. Thanks!

**Comment by pixelzoom** [comment]
According to @ariel-phet, the custom look of the slider track in Molarity can be changed to a standard HSlider track.  (This is good, since HSlider currently doesn't allow customization of the track.)

So I should be able to use a rotate HSlider via composition in VerticalSlider's constructor.

**Comment by pixelzoom** [comment]
Note that since this issue changes the look of the sim, we'll need to also revise the screenshot.

**Comment by pixelzoom** [comment]
Hmmm...  I may be able to make the track look the same by adding `cornerRadius:0` option to HSliderTrack, propagated through HSlider.

**Comment by pixelzoom** [comment]
@zepumph  @samreid FYI... Switching to HSlider is going to break the PhET-iO API.  VerticalSlider will have a different internal structure, and therefore different tandem, with different ids.

**Comment by pixelzoom** [comment]
My first PhET-iO sim is Molarity, the first PhET-iO release was 7/7/17 (7 days ago), and I'm already breaking the API.

**Comment by pixelzoom** [comment]
HSlider was enhanced in https://github.com/phetsims/sun/issues/302. So yes, we can reproduce the "look" of the track.

**Comment by pixelzoom** [comment]
I made these changes only in master.  If we want to patch this in the 1.3 release branch, it will require cherry picking MOLARITY.VerticalSlider and SUN.HSlider.   This work was done to facilitate keyboard navigation (#37), so I'll ask about the patch requirements there.  If keyboard navigation is going to be done in master, then there's no need to patch 1.3.   

In any case, this change will require QA spot-testing on a couple of platforms.

**Comment by pixelzoom** [comment]
@zepumph I think it probably makes sense for you to have a look at this, since (I think) you're going to be working on adding keyboard navigation.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/molarity/issues/37#issuecomment-315458335, @jessegreenberg said:
> ... Keyboard navigation will only be added to master, we won't be patching it into 1.3.

So I won't be patching this change into 1.3.  

The next release will therefore be from a new release branch, and will undergo a full QA test. @phet-steele Would you mind testing [1.4.0-dev.1](http://www.colorado.edu/physics/phet/dev/html/molarity/1.4.0-dev.1/molarity_en.html) to see if there are any obvious problems? One platform should be sufficient.

**Comment by phet-steele** [comment]
@pixelzoom, feels and looks great on macOS 10.12.5 Chrome and Win 10 Edge.

**Comment by pixelzoom** [comment]
@zepumph if this looks good to you, feel free to close.

**Comment by ariel-phet** [comment]
That is one nice looking slider :)

**Comment by zepumph** [comment]
Hey thanks for doing the keyboard navigation for me =) 
http://www.colorado.edu/physics/phet/dev/html/molarity/1.4.0-dev.1/molarity_en.html?accessibility


All looks good here. Thanks @pixelzoom.

**Comment by ariel-phet** [comment]
One side comment here for both @jessegreenberg and @zepumph 

I think we are seeing the real power of common code here. It seems part of the a11y work should really be pushing for sims to everywhere possible use common components. It is pretty powerful to go to a sim and basically have it working for keyboard nav "out of the box". And perhaps also pushing for components that do not currently have a great common code structure (or are not yet common), to be worked on as part of the the a11y work. It seems that dialog is a good example where this work goes hand in hand, and with some upfront investment, pays some very good maintenance and consistency dividends in the long run.
