### ISSUE TITLE
custom slider track is messed up

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#41]
Should look like this, as in published version 1.3.0:

![screenshot_339](https://user-images.githubusercontent.com/3046552/29145527-d32d38aa-7d1a-11e7-9291-5fcf81ccbf27.png)

Looks like this in master:

![screenshot_340](https://user-images.githubusercontent.com/3046552/29145533-d8cdbd52-7d1a-11e7-94b3-ab4e2fcb2b75.png)

**Comment by pixelzoom** [comment]
No related commits to molarity repository since 1.3.0 was published.   So this must be due to common-code changes, probably scenery.  @jonathanolson any idea?

**Comment by pixelzoom** [comment]
The relevant HSlider is created in molarity.VerticalSlider:

```js
 var sliderNode = new HSlider( property, range, {
      trackSize: new Dimension2( trackSize.height, trackSize.width ), // swap dimensions
      trackFillEnabled: 'black',
      trackStroke: 'rgb( 200, 200, 200 )',
      trackLineWidth: 13,
      trackCornerRadius: 10,
      thumbSize: new Dimension2( 30, 68 ), // in horizontal orientation!
      thumbFillEnabled: THUMB_NORMAL_COLOR,
      thumbFillHighlighted: THUMB_HIGHLIGHT_COLOR,
      rotation: -Math.PI / 2, // vertical orientation, max at top, min at bottom
      tandem: tandem.createTandem( 'sliderNode' )
    } );
```

**Comment by jonathanolson** [comment]
Looking into it.

**Comment by pixelzoom** [comment]
HSlider has been modified by @samreid @jessegreenberg and @mbarlow12 since this sim was published.

**Comment by pixelzoom** [comment]
HSliderTrack has been modified by @samreid and @zepumph since this sim was published.

**Comment by samreid** [comment]
Uh-oh, I'm the Venn diagram winner.

**Comment by jonathanolson** [comment]
It looks like the stroke on the enabledTrack is covering up the fill completely (lineWidth is 13, the "width" (height because it's rotated) is 6).

**Comment by samreid** [comment]
This may have broken in https://github.com/phetsims/sun/commit/e1d62999cacb686393a8338d5dda4e19f5160ba4

**Comment by jonathanolson** [comment]
I'm all sorts of confused with the naming of the "disabledTrack", since it looks like the background. The commit https://github.com/phetsims/sun/commit/e1d62999cacb686393a8338d5dda4e19f5160ba4 appears to have "fixed" the code, but then molarity's large (13) lineWidth covers the fill entirely.

I'm really not sure what the desired behavior should be, but could revert to having a lineWidth of 1 on the enabledTrack to go back to the "old" behavior.

Assigning to @samreid and @pixelzoom to figure out how it should be (I haven't been involved with the slider track before).

**Comment by pixelzoom** [comment]
Using `trackLineWidth:1` looks like this, definitely not what is desired:

![screenshot_344](https://user-images.githubusercontent.com/3046552/29146521-c49441ea-7d1e-11e7-8742-d259fb9b4216.png)

**Comment by jonathanolson** [comment]
Well the lineWidth is used both for the background (grey) and foreground (black). It makes sense to have no stroke on the foreground (black) rectangle in this case?

**Comment by pixelzoom** [comment]
Not sure why this ever worked in the first place, but fixed in the above commit.  Now looks like this:

![screenshot_345](https://user-images.githubusercontent.com/3046552/29146680-cf685128-7d1f-11e7-82ce-eade0690c12b.png)

**Comment by jonathanolson** [comment]
I "reverted" by removing the lineWidth on the enabledTrack. Presumably you can discuss whether a 1px stroke on the enabledTrack is appropriate, and whether it would need a separate parameter to adjust.

**Comment by samreid** [comment]
The solution @pixelzoom provided is more general, we should still provide lineWidth on the enabledTrack.

**Comment by samreid** [comment]
Thanks! Closing.

**Comment by pixelzoom** [comment]
Correct - a 1px stroke is not appropriate, that was the purpose of HSlider options.trackLineWidth.
