### ISSUE TITLE
Google form user suggestion: add NaCl

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molarity#42]
"Dear Developer,

I was wondering if NaCl could be added to the following simulation: https://phet.colorado.edu/sims/html/molarity/latest/molarity_en.html.

I was looking to develop an activity for students that discusses saline solutions of different concentration and their applications in medicine, in particular for IVs.  I have a number of nursing students in my General Chemistry class, but I think it would be of interest to any student taking chemistry.

Thank you for your time and consideration.

Best,

Dermot Donnelly"

**Comment by pixelzoom** [comment]
Adding a new solute to Molarity is relatively straightforward. I would need to know:

• name
• formula
• saturated concentration (moles/L)
• color of the solution at the smallest non-zero concentration
• color of the solution for at the saturated concentration
• color of precipitate particles
• where the new solute should appear in the combo box

... then add a new `Solute` to the `this.solutes` array in `MolarityModel`.

Since this sim's lead designer is no longer with the project, assigning to @ariel-phet to decide how to proceed.

**Comment by pixelzoom** [comment]
Since this sim's lead designer is no longer with the project, assigning to @ariel-phet to decide how to proceed.

**Comment by ariel-phet** [comment]
@pixelzoom we made this addition for concentration/beer's law. Please correct me if I am wrong, but I think all the info you need can likely be copied from that sim (and would be good to make them consistent anyhow). So I think...

- Name: Sodium chloride 
- Formula: NaCl
- Combo box: last position
- Other: color and such match to the Concentration sim

Does that seem reasonable?

**Comment by pixelzoom** [comment]
@ariel-phet asked:
> Does that seem reasonable?

Sort of.  But Beer's Law Lab is quite a bit different, and I'm wondering if NaCl really works in Molarity.  

First, please confirm that the saturated concentration of NaCl is 6.15M.  This value is not stated explicitly in the Beer's Law Lab model, it's derived, and it's tied to the color range.  If 6.15M is correct, then (given the range of solute amount and volume) it is impossible to saturate the solution in Molarity. 

Second, please have a look at [1.4.0-dev..2](http://www.colorado.edu/physics/phet/dev/html/molarity/1.4.0-dev.2/molarity_en.html), and note how the color of NaCl (in solution) is only very subtly different from water. There is also very little difference in the color gradient used to represent concentration (see screenshot below).  This color issues seems problematic to me.

So I'm wondering if there weren't good reasons for not adding NaCl to this sim.

![screenshot_369](https://user-images.githubusercontent.com/3046552/29830766-5e7d6440-8ca0-11e7-8139-9dce935f9ba7.png)

**Comment by pixelzoom** [comment]
Zoom call with @ariel-phet:  He's going to ask @oliver-phet to ask the customer if these limitation are acceptable.  The limitations are:
(1) It is not possible to saturate the solution with NaCl.
(2) The color difference between water and NaCl is subtle.
(3) The color difference between different concentrations of NaCl are subtle.

**Comment by oliver-phet** [comment]
Email to user sent.

**Comment by oliver-phet** [comment]
Reply from user:
> It's okay.  What I'm probably looking for is a different simulation then given the saturation consideration.  It was just an idea.  Thank you.

**Comment by pixelzoom** [comment]
@ariel-phet How do you want to proceed? Revert? Ask one of the chemists?

**Comment by pixelzoom** [comment]
@ariel-phet Did you mean to assign a chemist? Or tell me to revert?  I'd prefer not to leave "intermediate" changes like this hanging around.  You never know when a rogue PhET-iO branch might be created :)

**Comment by ariel-phet** [comment]
@pixelzoom please revert and close the issue

@oliver-phet can you let the user know about our concentration sim that DOES include salt?

**Comment by pixelzoom** [comment]
@ariel-phet said:
> @pixelzoom please revert and close the issue

Will do.

**Comment by pixelzoom** [comment]
NaCl removed.

@oliver-phet feel free to close this issue after you've done https://github.com/phetsims/molarity/issues/42#issuecomment-325830911.
