### ISSUE TITLE
Add to the instrumented PhET-iO list.

### ISSUE THREAD

**Issue by samreid** [phetsims/molarity#45]
@zepumph can we add this sim to the list of instrumented PhET-iO simulations?  It seems like we worked on this a while ago but I don't see any records if it being shared to clients.

**Comment by zepumph** [comment]
>list of instrumented PhET-iO simulations

I'm not sure I understand what this means. I see it in both `(testable-)phet-io` lists in perennial. It has a latest published version in the sim status spreadsheet (1.3.0-phetio).

**Comment by zepumph** [comment]
What if we had a script that would go through the sim status spreadsheet and get the current latest list of sim links based on that spreadsheet (provided that that document can stay up to date).

**Comment by pixelzoom** [comment]
I see molarity in perennial/data/phet-io.  @samreid @zepumph is there anything else to do here?

**Comment by samreid** [comment]
It appears @kathy-phet was informed and also shared these to clients in https://github.com/phetsims/phet-io/issues/1157#issuecomment-322323739

Molarity is not mentioned in https://github.com/phetsims/perennial/blob/ea4500c8fdeb65c88d99be1aab1e2cffad30d598/data/phet-io-maintenance.json, does it need a maintenance release or republication?

**Comment by pixelzoom** [comment]
@samreid Who is the above question directed to? What needs to be done to close this issue?

**Comment by samreid** [comment]
We are preparing an RC, that seems sufficient.  Closing.
