### ISSUE TITLE
title case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#50]
For https://github.com/phetsims/tasks/issues/953
Should "Show values" checkbox be in tile case?

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Yes, I would update the string to "Show Values". It's not a pressing issue, so it can wait until the sim is worked on again.

**Comment by pixelzoom** [comment]
Changed to title case in master, see screenshot below. Labeling as "fixed-awaiting-deploy".

![screenshot_823](https://user-images.githubusercontent.com/3046552/47887946-80181780-de07-11e8-9078-72b528fbb8d9.png)

**Comment by arouinfar** [comment]
Thanks @pixelzoom!

**Comment by pixelzoom** [comment]
I don't like this in general, because they are not titles, they are commands.  But I'll roll with it.

**Comment by pixelzoom** [comment]
I don't like this in general, because "Show values" is not a title, it's a command.  But I'll roll with it.

**Comment by terracoda** [comment]
The label for the checkbox is now "Solution Values" not "Show Values" in both the visual view and the accessible view.

This issue is stale and I think it can be closed.

**Comment by terracoda** [comment]
Since no one is assigned, I will go ahead and close. Please re-open if need be.
