### ISSUE TITLE
404 error in instance proxies

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molarity#53]
Found while testing https://github.com/phetsims/special-ops/issues/122.
When trying to open the molarity 1.4.3-rc.1 phet-io Instance Proxies link a 404 error appears instead.  This occurs both on iPad and Laptop.

**Comment by phet-steele** [comment]
I don't know how the link in https://github.com/phetsims/special-ops/issues/122 is generated, but the 1.4 branch of this sim was updated to studio in phetsims/QA/issues/161 so this should work: https://phet-dev.colorado.edu/html/molarity/1.4.3-rc.1/phet-io/wrappers/studio/studio.html

**Comment by pixelzoom** [comment]
This bug is specific to phetio, and (if I'm interpreting @phet-steele's comment correctly) it sounds like a bad URL was generated.   Assigning to @samreid and @zepumph to investigate.

**Comment by zepumph** [comment]
>it sounds like a bad URL was generated. 

I'm not sure how the automated maintenance release process works, if the links are generated. @samreid can you please note that the link in the rc was wrong for molarity, and recommend how to update this in the maintenance release process?

**Comment by samreid** [comment]
@KatieWoe after https://github.com/phetsims/molarity/issues/53#issuecomment-434856834 did you do testing of Molarity Studio?

**Comment by KatieWoe** [comment]
@samreid I hadn't.  I'll do that today.

**Comment by KatieWoe** [comment]
@samreid just tested with studio in the url and it looks ok.

**Comment by samreid** [comment]
Thanks, closing.
