### ISSUE TITLE
replace SoluteIO ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#54]
In SoluteIO.js:

`//TODO replace this with StateObjectIO, see phetsims/phet-io#1100`

phetsims/phet-io#1100 is closed and `StateObjectIO` no longer exists.  Please advise on what needs to be done here.

**Comment by samreid** [comment]
I'm presuming this issue is referring to SoluteIO.js.

**Comment by pixelzoom** [comment]
Ah yes, SoluteIO.js -- type fixed above.

**Comment by samreid** [comment]
I feel like SoluteIO is in good shape, it is not too complicated and what boilerplate code it does have, it is unclear how we would factor it out.  Marking for discussion with @zepumph and @chrisklus on Wednesday to double check and discuss further.

**Comment by zepumph** [comment]
Discussed at phet-io team meeting today. We like that SoluteIO has a descriptive name and a place for type specific documentation. For example seeing 
`PropertyIO.<SoluteIO>` would be much better in studio than `PropertyIO.<StateObjectIO>`

We do agree though that its reference-like qualities for serialization should be factored out. All the type checking can happen in a new type `ReferenceIO.js`, This type would know how to go from instance -> phetioID (toStateObject), and then from phetioID back to instance (fromStateObject). Here is what SoluteIO could look like afterwards.

```js
// Copyright 2017-2018, University of Colorado Boulder

//TODO replace this with StateObjectIO, https://github.com/phetsims/molarity/issues/54
/**
 * IO type for Solute
 *
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( function( require ) {
  'use strict';

  // modules
  var molarity = require( 'MOLARITY/molarity' );
  var ReferenceIO = require( 'TANDEM/types/ReferenceIO' );
  var phetioInherit = require( 'TANDEM/phetioInherit' );

  /**
   * @param {Solute} solute
   * @param {string} phetioID
   * @constructor
   */
  function SoluteIO( solute, phetioID ) {
    ReferenceIO.call( this, solute, phetioID );
  }

  phetioInherit( ReferenceIO, 'SoluteIO', SoluteIO, {}, {
    documentation: 'The solute for the sim',
  } );

  return molarity.register( 'SoluteIO', SoluteIO );
} );

```

Assigning to @samreid  to investigate. Let us know if you help.

**Comment by pixelzoom** [comment]
@samreid @zepumph so is there anything to be done here?  Or shall we close and revisit SoluteIO during PhET-iO redesign #51?

**Comment by samreid** [comment]
I added ReferenceIO and used it for SoluteIO.  Seems to be working ok in studio=>launch.  @zepumph can you take a look?

**Comment by zepumph** [comment]
Things are looking pretty good while looking at the code. Full review is on hold until https://github.com/phetsims/tandem/issues/85 is sort out.

**Comment by zepumph** [comment]
This is all looking really good. Now SoluteIO looks like:

```

Solute.SoluteIO = new IOType( 'SoluteIO', {
  valueType: Solute,
  documentation: 'The solute for the sim',
  supertype: ReferenceIO( IOType.ObjectIO )
} );
```
