### ISSUE TITLE
create a dev version of current a11y work

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#62]
This means that we will create a one-off version of the content in the screen-summary branch that @twant has been working on. Since one-off branches need to be camel cased, I will make a new branch, `screenSummary`, from the old branch and do the publication from that. I will then delete the hyphenated branch. Tagging @twant so that she knows to use the screenSummary branch from now on.

**Comment by zepumph** [comment]
@emily-phet (I couldn't find Matthew's handle), here is the current version of Molarity. 

There should be alerts when moving the sliders with the arrow keys.
NOTE: Right now please only use the up and down arrow keys to use the slider (not left and right).

https://phet-dev.colorado.edu/html/molarity/1.5.0-screenSummary.1/phet/molarity_en_phet.html?a11y

**Comment by pixelzoom** [comment]
@zepumph is looks like the dev version has been created.  Can this issue be closed?

**Comment by zepumph** [comment]
Yes thank you.
