### ISSUE TITLE
MolarityAlertManager issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#68]
Issues with MolarityAlertManager:

(1) The constructor has the same problem as https://github.com/phetsims/molarity/issues/67.  `model` is unnecessary.  

(2) `this.solutions` does not need to be a field.  It is marked `@private` and  is used only in the constructor.

(3) `this.solutionDescriber` does not need to be a field.  It is marked `@private` and  is used only in the constructor.

(4) `getAlertManager` is not used.

**Comment by pixelzoom** [comment]
@zepumph fyi.

**Comment by twant** [comment]
@pixelzoom I think I addressed the parts of this issue in MolarityAlertManager. I started working on #67, but not all of those concerns have been addressed yet -- will let you know when they are. Thanks for looking over these, and for your feedback!

**Comment by pixelzoom** [comment]
Looks great @twant, closing.
