### ISSUE TITLE
MolarityKeyboardHelpContent questions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molarity#69]
Why is `MolarityKeyboardHelpContent` not a subclass of `SCENERY/HelpContent`?

Why is it necessary to nest `MolarityKeyboardHelpContent` in an HBox as the only child?

**Comment by zepumph** [comment]
Please see https://github.com/phetsims/tasks/issues/994. This issue is a naming convention one. Closing as duplicate.
