### ISSUE TITLE
Add aria-valuetext to sliders?

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#71]
As part of previous discussion, I thought we wanted to add aria-valuetext to the sliders, and to have them different on focus than on value change. Though now I can't find this in the design doc.

No matter, @twant, from https://github.com/phetsims/scenery/issues/951 this is now simply supported through the api for `AccessibleSlider` (or to be more specific, `AccessibleValueHandler` which is mixed into `AccessibleSlider`).

@twant please see these two options that can be passed into the VSlider instance created in `VerticalSlider`. 

https://github.com/phetsims/sun/blob/fae62bd23a499bab48b60ebd53c61925e2388365/js/accessibility/AccessibleValueHandler.js#L80-L102

feel free to explore all of the options in that file, they are all supported by the sliders. I'm not sure what is best for Molarity's needs.

Let me know if you would like some assistance when it comes to passing through VerticalSlider, because that could get a bit messy.

**Comment by twant** [comment]
Thanks, @zepumph! I think the one that will work best is `a11yCreateValueChangeAriaValueText`, but it would need to track two properties in order to work. Would love to discuss this week to see how implementation looks for two tracked properties!

**Comment by twant** [comment]
Closing here, as the most up-to-date issues with aria-valueText are tracked in https://github.com/phetsims/molarity/issues/82
