### ISSUE TITLE
MolarityKeyboardHelpContent may not be necessary

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/molarity#76]
Just noticed during https://github.com/phetsims/scenery-phet/issues/478. Since the GeneralKeyboardHelpSection is the only content for the KeyboarHelpDialog it likely doesn't need to be contained in an HBox. In fact, we could probably get away with passing a GeneralKeyboardHelpSection to `keyboardHelpNode` option in molarity-main and delete MolarityKeyboarHelpContent. @twant what do you think?

**Comment by twant** [comment]
@jessegreenberg I think that makes a lot of sense. Based on updates to the design doc, I think the help content now needs to have more than GeneralKeyboardHelpSection, so I've kept MolarityKeyboardHelpContent for now. I just pushed some changes with the updated content. Let me know what you think, and if there's still a way to consolidate or eliminate the need for MolarityKeyboardHelpSection!

**Comment by jessegreenberg** [comment]
I see, thanks@twant! With other content it makes sense to keep MolarityKeyboardHelpContent. Closing.
