### ISSUE TITLE
Refactor MolarityDescriber into modular sections

### ISSUE THREAD

**Issue by zepumph** [phetsims/molarity#79]
From https://github.com/phetsims/molarity/issues/67#issuecomment-480957105, @zepumph and @twant will investigate pulling pieces of MolarityDescriber into more modular sections. Hopefully this will limit the complexity of MolarityDescriber, and potentially remove it all together.

We don't like that currently it stands as a sort of "describer view" that is separate from the screen view. Perhaps the "entry points" in Molarity describer can be outsourced to the screenview, and the logic to the nested describers.

**Comment by twant** [comment]
Working on master now, so closed the issue related to the molarityDescriberRefactor branch

**Comment by twant** [comment]
@zepumph does this look ready to close to you?

**Comment by zepumph** [comment]
Yes I think so.
