### ISSUE TITLE
Two small changes in the a11y design document

### ISSUE THREAD

**Issue by Matthew-phet** [phetsims/molarity#81]
@emily-phet and I changed a couple things in the [a11y] design doc.

- [x] We removed the "peak" related wording and added the concentration readout range.

    - [Example New Wording, change in italics] 
Solution Concentration of {{Potassium permanganate}} Is {{Very Concentrated}}. _Concentration readout range is {{0.00}} to {{5.0 M}}_. The chemical formula for {{Potassium permanganate}} is {{KMnO4}}

    - [Example of the Original Wording] 
Solution Concentration of ‪Potassium chromate‬ Is not concentrated the peak of this solute is 3.35 Molar. The chemical formula for ‪Potassium chromate‬ is K2CrO4.

- [x] On selecting a new solute from the combobox the following alerts should play on change of saturated/unsaturated state: 

    - **Change from unsaturated to saturated - Saturation Alert**
Solution saturated. Beyond max concentration, solids appear.

    - **Change from saturated to unsaturated - Saturated Alert**
Solution no longer saturated. Solution {{very concentrated}}, solids dissolve.

**Comment by twant** [comment]
@Matthew-phet are these changes ready for implementation? Feel free to assign this issue to me when you feel like they are :)

**Comment by Matthew-phet** [comment]
Yeah! these changes are ready for implementation.

**Comment by emily-phet** [comment]
@twant  - @Matthew-phet is new to GitHub issues, so I had asked him to assign me so I could make wording suggestions if needed. I didn't respond very quickly though, so thanks for checking in!

I made a few edits above (just formatting and wording, nothing has changed regarding actual content)

**Comment by twant** [comment]
Got it -- sorry to jump the gun, @emily-phet and @Matthew-phet!

**Comment by twant** [comment]
@Matthew-phet I think this has been implemented -- let's review tomorrow at our meeting to make sure it sounds how it should!

**Comment by twant** [comment]
I believe this is also implemented: https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.10/phet/molarity_en_phet.html
