### ISSUE TITLE
Incorrect indication of "Zero" solute - Region for "a little" needs to be changed to 0.001-0.150

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#84]
When Show Values Unchecked and Solute slider just above zero:

`Currently, beaker is half full of a ‪Drink mix‬ ‬solution containing Zero ‪‪Drink mix‬‬ solute. Solution is not concentrated and is not yet saturated.`

is read out in the screen summary. We think the region when "a little" solute is indicated needs to be changed to be 0.001-0.150 to address this.

**Comment by pixelzoom** [comment]
Hi a11y team.   If you create an issue that is specific to a11y, please assign an appropriate label (`dev:a11y` or `design:a11y`).   It will help me with filtering issues for the large number of repos that I'm responsible for.   Thanks!

**Comment by twant** [comment]
@Matthew-phet @emily-phet Assigning these back over to you for review.
