### ISSUE TITLE
When Solute Amount Slider = 0, Alerts and Aria valutext

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#85]
For the case when when Solute Slider set to 0

- [x] Immediately upon slider value becoming 0 - Solute Slider alert: “No solute. Solution is pure water.

- [x] When solute slider = 0 and Solution Volume slider is moved to: 
(future) Aria Valuetext: **no change**, for example “Beaker over half full”
(future) Alerts: “[More/Less] water. No solute in beaker.”

**Comment by twant** [comment]
Per meeting with @Matthew-phet, we still need to turn the alert off after it's been read once, and then change the alert to "more/less water. No solute in beaker". Implemented so far is the alert once solute amount has become zero.

**Comment by twant** [comment]
@Matthew-phet @emily-phet Assigning these back over to you for review.
