### ISSUE TITLE
Correction for dynamic part of the Screen Summary

### ISSUE THREAD

**Issue by emily-phet** [phetsims/molarity#91]
When the Beaker is low, incorrect wording shown currently.

Instead of "Beaker is low of drink mix solution..." needs to be "Beaker has a low amount of drink mix solution...".

**Comment by twant** [comment]
I think this (and #90, #89, #88) have now been implemented, @emily-phet @Matthew-phet. Assigning back over to you to take a look/listen. 
https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.12/phet/molarity_en_phet.html
