### ISSUE TITLE
Show values checkbox alert read out twice

### ISSUE THREAD

**Issue by twant** [phetsims/molarity#94]
@zepumph and @terracoda, as @emily-phet, @Matthew-phet and I were listening to Molarity, we noticed that when the checkbox was checked, the alert was read out twice. We also noticed this is GFLB. Do you know why this is happening? 

Separately, we also noticed that when we uncheck a checkbox, the alert read out first says "check checkbox", which seems to be the opposite action of what we just did. We saw the same behavior in GFLB. We're not sure if that's just normal checkbox behavior with a screen reader, or why this is happening, and figured you may know more about this!

**Comment by twant** [comment]
This also seems to be happening (where the alert is read out twice) when we press the "reset all" button. We're on VoiceOver, btw.

**Comment by terracoda** [comment]
@twant, I have experienced duplicate alerts many times when testing, mainly in A11y View and in Sonfication wrapper, and sometimes even in the sim.

Using Safari 12.1 and Voice Over on High Sierra 10.13.6 I am currently no getting repeat alerts. I am getting pile-ups in the utterance queue, though, when I move the sliders several steps. I'll open an issue for that so you and @zepumph can work on it.

**Comment by twant** [comment]
Great, thanks for taking a look! Ok to close this and continue documenting utteranceque pile-up issues in #98, @terracoda?
