### ISSUE TITLE
Labels for sliders - remove word "slider" from accessible name

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#97]
Screen reader software reads out the `role` of an interactive element automatically, so there is not need to have the word "slider" (or any `role` for that matter) in the element's `label`. The content of the label should just have the element's accessible name.

In the case of the sliders in Molarity the accessible names are:
-  Solute Amount
- Solution Volume

I am just checking with @Matthew-phet and @emily-phet to see if the units should be part of the name as well.

**Comment by terracoda** [comment]
We'll assign over to @twant after today's design meeting.

**Comment by emily-phet** [comment]
This was already on one of the issues that @twant created yesterday (listed as a checkbox item inside probably the Play Area-focused issue).
