### ISSUE TITLE
Alerts pile up in utterance queue

### ISSUE THREAD

**Issue by terracoda** [phetsims/molarity#98]
As mentioned in https://github.com/phetsims/molarity/issues/94#issuecomment-494381340, when I move the sliders a lot the alerts pile up rather than jumping to the latest alert according to the latest value.

Using Safari 12.1 and VoiceOver on MacOs High Sierra 10.13.6

**Comment by terracoda** [comment]
@twant, @zepumph might have some dev tricks to address this.

**Comment by zepumph** [comment]
@twant I would be happy to pair on this if you'd like. In the mean time, explore the `ValueChangeUtterance` subtype to see if this helps solve the problem. See OHMS_LAW/ControlPanel for example usage that seems to be very similar to yours. 

It would be good to familiarize yourself with the new Utterance api, especially `alertStable` and `alertStableDelay`. Notice that `alertStableDelay` is basically the only thing that makes ValueChangeUtterance special. Playing around with that delay number may help this process.

**Comment by twant** [comment]
@terracoda I've updated the alerts and pushed to master. They sound better, but I'm still noticing weird repeating behavior on them. I can't tell if this is just that VoiceOver sometimes repeats alerts, or if the alerts are actually piling up still. Do you mind taking a listen and seeing how it sounds to you?

**Comment by terracoda** [comment]
Awesome work @twant, no pile ups!  Thanks and closing.
